/**
 * UI string translations for the STNH Wiki interface.
 * Mod content (item names, descriptions) is handled separately by I18n.t().
 * This file handles navigation, tabs, filters, labels, messages etc.
 */
const UI_STRINGS = {
    // ==========================================
    // Navigation
    // ==========================================
    'ui.nav.hub': { english: 'Hub', german: 'Hub', french: 'Accueil', russian: 'Главная' , spanish: 'Portal', polish: 'Centrum', braz_por: 'Portal' },
    'ui.nav.events': { english: 'Events', german: 'Ereignisse', french: 'Événements', russian: 'События' , spanish: 'Eventos', polish: 'Wydarzenia', braz_por: 'Eventos' },
    'ui.nav.tech': { english: 'Technology', german: 'Technologie', french: 'Technologie', russian: 'Технологии' , spanish: 'Tecnolog\u00eda', polish: 'Technologia', braz_por: 'Tecnologia' },
    'ui.nav.ships': { english: 'Ships', german: 'Schiffe', french: 'Vaisseaux', russian: 'Корабли' , spanish: 'Naves', polish: 'Statki', braz_por: 'Naves' },
    'ui.nav.buildings': { english: 'Buildings', german: 'Geb\u00e4ude', french: 'B\u00e2timents', russian: 'Здания' , spanish: 'Edificios', polish: 'Budynki', braz_por: 'Edif\u00edcios' },
    'ui.nav.traits': { english: 'Traits', german: 'Eigenschaften', french: 'Traits', russian: 'Черты' , spanish: 'Rasgos', polish: 'Cechy', braz_por: 'Tra\u00e7os' },
    'ui.nav.governments': { english: 'Governance', german: 'Regierung', french: 'Gouvernance', russian: 'Управление' , spanish: 'Gobernanza', polish: 'Rz\u0105dy', braz_por: 'Governan\u00e7a' },
    'ui.nav.empire': { english: 'Empire', german: 'Imperium', french: 'Empire', russian: 'Империя' , spanish: 'Imperio', polish: 'Imperium', braz_por: 'Imp\u00e9rio' },
    'ui.nav.megastructures': { english: 'Megastructures', german: 'Megastrukturen', french: 'M\u00e9gastructures', russian: 'Мегаструктуры' , spanish: 'Megaestructuras', polish: 'Megastruktury', braz_por: 'Megaestruturas' },
    'ui.nav.anomalies': { english: 'Anomalies', german: 'Anomalien', french: 'Anomalies', russian: 'Аномалии' , spanish: 'Anomal\u00edas', polish: 'Anomalie', braz_por: 'Anomalias' },
    'ui.nav.empires': { english: 'Empires', german: 'Reiche', french: 'Empires', russian: 'Империи' , spanish: 'Imperios', polish: 'Imperia', braz_por: 'Imp\u00e9rios' },
    'ui.nav.economy': { english: 'Economy', german: 'Wirtschaft', french: '\u00c9conomie', russian: 'Экономика' , spanish: 'Econom\u00eda', polish: 'Gospodarka', braz_por: 'Economia' },
    'ui.nav.exploration': { english: 'Exploration', german: 'Erkundung', french: 'Exploration', russian: 'Исследование' , spanish: 'Exploraci\u00f3n', polish: 'Eksploracja', braz_por: 'Explora\u00e7\u00e3o' },
    'ui.nav.military': { english: 'Military', german: 'Milit\u00e4r', french: 'Militaire', russian: 'Военные' , spanish: 'Militar', polish: 'Wojsko', braz_por: 'Militar' },

    // ==========================================
    // Tab Buttons
    // ==========================================
    'ui.tab.ships': { english: 'Ships', german: 'Schiffe', french: 'Vaisseaux', russian: 'Корабли' , spanish: 'Naves', polish: 'Statki', braz_por: 'Naves' },
    'ui.tab.models': { english: 'Models', german: 'Modelle', french: 'Modèles', russian: 'Модели' , spanish: 'Modelos', polish: 'Modele', braz_por: 'Modelos' },
    'ui.tab.components': { english: 'Components', german: 'Komponenten', french: 'Composants', russian: 'Компоненты' , spanish: 'Componentes', polish: 'Komponenty', braz_por: 'Componentes' },
    'ui.tab.buildings': { english: 'Buildings', german: 'Geb\u00e4ude', french: 'Bâtiments', russian: 'Здания' , spanish: 'Edificios', polish: 'Budynki', braz_por: 'Edif\u00edcios' },
    'ui.tab.districts': { english: 'Districts', german: 'Bezirke', french: 'Districts', russian: 'Районы' , spanish: 'Distritos', polish: 'Dzielnice', braz_por: 'Distritos' },
    'ui.tab.traits': { english: 'Leader Traits', german: 'Führereigenschaften', french: 'Traits des chefs', russian: 'Черты лидеров' , spanish: 'Rasgos de l\u00edder', polish: 'Cechy przyw\u00f3dcy', braz_por: 'Tra\u00e7os de l\u00edder' },
    'ui.tab.traditions': { english: 'Traditions', german: 'Traditionen', french: 'Traditions', russian: 'Традиции' , spanish: 'Tradiciones', polish: 'Tradycje', braz_por: 'Tradi\u00e7\u00f5es' },
    'ui.tab.perks': { english: 'Ascension Perks', german: 'Aufstiegsvorteile', french: 'Atouts d’ascension', russian: 'Навыки возвышения' , spanish: 'Ventajas de ascensi\u00f3n', polish: 'Atuty wniebowst\u0105pienia', braz_por: 'Vantagens de ascens\u00e3o' },
    'ui.tab.governments': { english: 'Governments', german: 'Regierungen', french: 'Gouvernements', russian: 'Правительства' , spanish: 'Gobiernos', polish: 'Rz\u0105dy', braz_por: 'Governos' },
    'ui.tab.civics': { english: 'Civics', german: 'B\u00fcrgerrechte', french: 'Civiques', russian: 'Общественное устройство' , spanish: 'Doctrinas', polish: 'Ustroje', braz_por: 'Doutrinas' },
    'ui.tab.authorities': { english: 'Authorities', german: 'Autoritäten', french: 'Autorités', russian: 'Системы власти' , spanish: 'Autoridades', polish: 'W\u0142adze', braz_por: 'Autoridades' },
    'ui.tab.policies': { english: 'Policies', german: 'Richtlinien', french: 'Politiques', russian: 'Политики' , spanish: 'Pol\u00edticas', polish: 'Polityki', braz_por: 'Pol\u00edticas' },
    'ui.tab.edicts': { english: 'Edicts', german: 'Edikte', french: 'Édits', russian: 'Указы' , spanish: 'Edictos', polish: 'Edykty', braz_por: '\u00c9ditos' },
    'ui.tab.councilors': { english: 'Council', german: 'Rat', french: 'Conseil', russian: 'Совет' , spanish: 'Consejo', polish: 'Rada', braz_por: 'Conselho' },
    'ui.tab.megastructures': { english: 'Megastructures', german: 'Megastrukturen', french: 'Mégastructures', russian: 'Мегаструктуры' , spanish: 'Megaestructuras', polish: 'Megastruktury', braz_por: 'Megaestruturas' },
    'ui.tab.relics': { english: 'Relics', german: 'Relikte', french: 'Reliques', russian: 'Реликвии' , spanish: 'Reliquias', polish: 'Relikwie', braz_por: 'Rel\u00edquias' },
    'ui.tab.anomalies': { english: 'Anomalies', german: 'Anomalien', french: 'Anomalies', russian: 'Аномалии' , spanish: 'Anomal\u00edas', polish: 'Anomalie', braz_por: 'Anomalias' },
    'ui.tab.archaeology': { english: 'Archaeology', german: 'Archäologie', french: 'Archéologie', russian: 'Археология' , spanish: 'Arqueolog\u00eda', polish: 'Archeologia', braz_por: 'Arqueologia' },
    'ui.tab.empires': { english: 'Empires', german: 'Reiche', french: 'Empires', russian: 'Империи' , spanish: 'Imperios', polish: 'Imperia', braz_por: 'Imp\u00e9rios' },
    'ui.tab.species': { english: 'Species', german: 'Spezies', french: 'Espèces', russian: 'Виды' , spanish: 'Especies', polish: 'Gatunki', braz_por: 'Esp\u00e9cies' },
    'ui.tab.jobs': { english: 'Jobs', german: 'Berufe', french: 'Emplois', russian: 'Профессии' , spanish: 'Empleos', polish: 'Prace', braz_por: 'Empregos' },
    'ui.tab.deposits': { english: 'Deposits', german: 'Vorkommen', french: 'Gisements', russian: 'Залежи' , spanish: 'Yacimientos', polish: 'Z\u0142o\u017ca', braz_por: 'Dep\u00f3sitos' },
    'ui.tab.resources': { english: 'Resources', german: 'Ressourcen', french: 'Ressources', russian: 'Ресурсы' , spanish: 'Recursos', polish: 'Zasoby', braz_por: 'Recursos' },
    'ui.tab.technology': { english: 'Technology', german: 'Technologie', french: 'Technologie', russian: 'Технологии' , spanish: 'Tecnolog\u00eda', polish: 'Technologia', braz_por: 'Tecnologia' },
    'ui.view.list': { english: '☰ List', german: '☰ Liste', french: '☰ Liste', russian: '☰ Список' , spanish: '\u2630 Lista', polish: '\u2630 Lista', braz_por: '\u2630 Lista' },
    'ui.view.map': { english: '✦ Galaxy Map', german: '✦ Galaxie-Karte', french: '✦ Carte galactique', russian: '✦ Карта галактики' , spanish: '\u2726 Mapa gal\u00e1ctico', polish: '\u2726 Mapa galaktyki', braz_por: '\u2726 Mapa gal\u00e1ctico' },
    'ui.view.techtree': { english: '⌥ Tech Tree', german: '⌥ Technikbaum', french: '⌥ Arbre techno', russian: '⌥ Дерево технологий' , spanish: '\u2325 \u00c1rbol tecnol\u00f3gico', polish: '\u2325 Drzewo technologii', braz_por: '\u2325 \u00c1rvore tecnol\u00f3gica' },
    'ui.view.list_view': { english: '☰ List', german: '☰ Liste', french: '☰ Liste', russian: '☰ Список' , spanish: '\u2630 Lista', polish: '\u2630 Lista', braz_por: '\u2630 Lista' },
    'ui.view.tree_view': { english: '⌥ Tree', german: '⌥ Baum', french: '⌥ Arbre', russian: '⌥ Дерево' , spanish: '\u2325 \u00c1rbol', polish: '\u2325 Drzewo', braz_por: '\u2325 \u00c1rvore' },

    // ==========================================
    // Filter Labels & Default Options
    // ==========================================
    'ui.filter.class': { english: 'Class', german: 'Klasse', french: 'Classe', russian: 'Класс' , spanish: 'Clase', polish: 'Klasa', braz_por: 'Classe' },
    'ui.filter.all_classes': { english: 'All Classes', german: 'Alle Klassen', french: 'Toutes les classes', russian: 'Все классы' , spanish: 'Todas las clases', polish: 'Wszystkie klasy', braz_por: 'Todas as classes' },
    'ui.filter.size': { english: 'Size', german: 'Gr\u00f6\u00dfe', french: 'Taille', russian: 'Размер' , spanish: 'Tama\u00f1o', polish: 'Rozmiar', braz_por: 'Tamanho' },
    'ui.filter.all_sizes': { english: 'All Sizes', german: 'Alle Gr\u00f6\u00dfen', french: 'Toutes les tailles', russian: 'Все размеры' , spanish: 'Todos los tama\u00f1os', polish: 'Wszystkie rozmiary', braz_por: 'Todos os tamanhos' },
    'ui.filter.type': { english: 'Type', german: 'Typ', french: 'Type', russian: 'Тип' , spanish: 'Tipo', polish: 'Typ', braz_por: 'Tipo' },
    'ui.filter.all_types': { english: 'All Types', german: 'Alle Typen', french: 'Tous les types', russian: 'Все типы' , spanish: 'Todos los tipos', polish: 'Wszystkie typy', braz_por: 'Todos os tipos' },
    'ui.filter.category': { english: 'Category', german: 'Kategorie', french: 'Cat\u00e9gorie', russian: 'Категория' , spanish: 'Categor\u00eda', polish: 'Kategoria', braz_por: 'Categoria' },
    'ui.filter.all_categories': { english: 'All Categories', german: 'Alle Kategorien', french: 'Toutes les cat\u00e9gories', russian: 'Все категории' , spanish: 'Todas las categor\u00edas', polish: 'Wszystkie kategorie', braz_por: 'Todas as categorias' },
    'ui.filter.show_unused': { english: 'Show unused', german: 'Ungenutzte zeigen', french: 'Afficher inutilis\u00e9es', russian: 'Показать неиспользуемые' , spanish: 'Mostrar no usados', polish: 'Poka\u017c nieu\u017cywane', braz_por: 'Mostrar n\u00e3o usados' },
    'ui.filter.tree': { english: 'Tree', german: 'Baum', french: 'Arbre', russian: 'Дерево' , spanish: '\u00c1rbol', polish: 'Drzewo', braz_por: '\u00c1rvore' },
    'ui.filter.all_trees': { english: 'All Trees', german: 'Alle B\u00e4ume', french: 'Tous les arbres', russian: 'Все деревья' , spanish: 'Todos los \u00e1rboles', polish: 'Wszystkie drzewa', braz_por: 'Todas as \u00e1rvores' },
    'ui.filter.level': { english: 'Level', german: 'Stufe', french: 'Niveau', russian: 'Уровень' , spanish: 'Nivel', polish: 'Poziom', braz_por: 'N\u00edvel' },
    'ui.filter.all_levels': { english: 'All Levels', german: 'Alle Stufen', french: 'Tous les niveaux', russian: 'Все уровни' , spanish: 'Todos los niveles', polish: 'Wszystkie poziomy', braz_por: 'Todos os n\u00edveis' },
    'ui.filter.authority': { english: 'Authority', german: 'Autorit\u00e4t', french: 'Autorit\u00e9', russian: 'Система власти' , spanish: 'Autoridad', polish: 'W\u0142adza', braz_por: 'Autoridade' },
    'ui.filter.all_authorities': { english: 'All Authorities', german: 'Alle Autorit\u00e4ten', french: 'Toutes les autorit\u00e9s', russian: 'Все системы власти' , spanish: 'Todas las autoridades', polish: 'Wszystkie w\u0142adze', braz_por: 'Todas as autoridades' },
    'ui.filter.archetype': { english: 'Archetype', german: 'Archetyp', french: 'Arch\u00e9type', russian: 'Архетип' , spanish: 'Arquetipo', polish: 'Archetyp', braz_por: 'Arqu\u00e9tipo' },
    'ui.filter.all_archetypes': { english: 'All Archetypes', german: 'Alle Archetypen', french: 'Tous les arch\u00e9types', russian: 'Все архетипы' , spanish: 'Todos los arquetipos', polish: 'Wszystkie archetypy', braz_por: 'Todos os arqu\u00e9tipos' },
    'ui.filter.faction': { english: 'Faction', german: 'Fraktion', french: 'Faction', russian: 'Фракция' , spanish: 'Facci\u00f3n', polish: 'Frakcja', braz_por: 'Fac\u00e7\u00e3o' },
    'ui.filter.all_factions': { english: 'All Factions', german: 'Alle Fraktionen', french: 'Toutes les factions', russian: 'Все фракции' , spanish: 'Todas las facciones', polish: 'Wszystkie frakcje', braz_por: 'Todas as fac\u00e7\u00f5es' },
    'ui.filter.namespace': { english: 'Namespace', german: 'Namensraum', french: 'Espace de noms', russian: 'Пространство имён' , spanish: 'Espacio de nombres', polish: 'Przestrze\u0144 nazw', braz_por: 'Namespace' },
    'ui.filter.all_namespaces': { english: 'All Namespaces', german: 'Alle Namensr\u00e4ume', french: 'Tous les espaces de noms', russian: 'Все пространства имён' , spanish: 'Todos los espacios de nombres', polish: 'Wszystkie przestrzenie nazw', braz_por: 'Todos os namespaces' },
    'ui.filter.show_hidden': { english: 'Show Hidden', german: 'Versteckte anzeigen', french: 'Afficher les cach\u00e9s', russian: 'Показать скрытые' , spanish: 'Mostrar ocultos', polish: 'Poka\u017c ukryte', braz_por: 'Mostrar ocultos' },
    'ui.filter.triggered_only': { english: 'Triggered Only', german: 'Nur ausgel\u00f6ste', french: 'D\u00e9clench\u00e9s uniquement', russian: 'Только триггерные' , spanish: 'Solo activado', polish: 'Tylko wyzwalane', braz_por: 'Apenas acionado' },
    'ui.filter.origins_only': { english: 'Origins only', german: 'Nur Urspr\u00fcnge', french: 'Origines uniquement', russian: 'Только происхождения' , spanish: 'Solo or\u00edgenes', polish: 'Tylko pochodzenia', braz_por: 'Apenas origens' },
    'ui.filter.area': { english: 'Area', german: 'Bereich', french: 'Domaine', russian: 'Область' , spanish: '\u00c1rea', polish: 'Dziedzina', braz_por: '\u00c1rea' },
    'ui.filter.all_areas': { english: 'All Areas', german: 'Alle Bereiche', french: 'Tous les domaines', russian: 'Все области' , spanish: 'Todas las \u00e1reas', polish: 'Wszystkie dziedziny', braz_por: 'Todas as \u00e1reas' },
    'ui.filter.physics': { english: 'Physics', german: 'Physik', french: 'Physique', russian: 'Физика' , spanish: 'F\u00edsica', polish: 'Fizyka', braz_por: 'F\u00edsica' },
    'ui.filter.engineering': { english: 'Engineering', german: 'Ingenieurwesen', french: 'Ingénierie', russian: 'Инженерия' , spanish: 'Ingenier\u00eda', polish: 'In\u017cynieria', braz_por: 'Engenharia' },
    'ui.filter.society': { english: 'Society', german: 'Gesellschaft', french: 'Société', russian: 'Общество' , spanish: 'Sociedad', polish: 'Spo\u0142ecze\u0144stwo', braz_por: 'Sociedade' },
    'ui.filter.tier': { english: 'Tier', german: 'Stufe', french: 'Niveau', russian: 'Уровень' , spanish: 'Nivel', polish: 'Poziom', braz_por: 'N\u00edvel' },
    'ui.filter.tier_x': { english: 'Tier %n', german: 'Stufe %n', french: 'Niveau %n', russian: 'Уровень %n' , spanish: 'Nivel %n', polish: 'Poziom %n', braz_por: 'N\u00edvel %n' },
    'ui.filter.min_tier': { english: 'Min Tier', german: 'Mindeststufe', french: 'Niveau min', russian: 'Мин. уровень' , spanish: 'Nivel m\u00edn.', polish: 'Min. poziom', braz_por: 'N\u00edvel m\u00edn.' },
    'ui.filter.max_tier': { english: 'Max Tier', german: 'Maximalstuf', french: 'Niveau max', russian: 'Макс. уровень' , spanish: 'Nivel m\u00e1x.', polish: 'Maks. poziom', braz_por: 'N\u00edvel m\u00e1x.' },
    'ui.filter.show_no_model': { english: 'Show ships without 3D model', german: 'Schiffe ohne 3D-Modell anzeigen', french: 'Afficher les vaisseaux sans mod\u00e8le 3D', russian: 'Показать корабли без 3D-модели' , spanish: 'Mostrar naves sin modelo 3D', polish: 'Poka\u017c statki bez modelu 3D', braz_por: 'Mostrar naves sem modelo 3D' },

    // Event types
    'ui.event_type.country_event': { english: 'Country', german: 'Land', french: 'Pays', russian: 'Страна' , spanish: 'Pa\u00eds', polish: 'Pa\u0144stwo', braz_por: 'Pa\u00eds' },
    'ui.event_type.ship_event': { english: 'Ship', german: 'Schiff', french: 'Vaisseau', russian: 'Корабль' , spanish: 'Nave', polish: 'Statek', braz_por: 'Nave' },
    'ui.event_type.planet_event': { english: 'Planet', german: 'Planet', french: 'Plan\u00e8te', russian: 'Планета' , spanish: 'Planeta', polish: 'Planeta', braz_por: 'Planeta' },
    'ui.event_type.fleet_event': { english: 'Fleet', german: 'Flotte', french: 'Flotte', russian: 'Флот' , spanish: 'Flota', polish: 'Flota', braz_por: 'Frota' },
    'ui.event_type.situation_event': { english: 'Situation', german: 'Situation', french: 'Situation', russian: 'Ситуация' , spanish: 'Situaci\u00f3n', polish: 'Sytuacja', braz_por: 'Situa\u00e7\u00e3o' },
    'ui.event_type.observer_event': { english: 'Observer', german: 'Beobachter', french: 'Observateur', russian: 'Наблюдатель' , spanish: 'Observador', polish: 'Obserwator', braz_por: 'Observador' },
    'ui.event_type.pop_event': { english: 'Pop', german: 'Bevölkerung', french: 'Population', russian: 'Пласт' , spanish: 'Poblaci\u00f3n', polish: 'Populacja', braz_por: 'Popula\u00e7\u00e3o' },

    // Ship class labels
    'ui.ship_class.military': { english: 'Military', german: 'Milit\u00e4r', french: 'Militaire', russian: 'Военный' , spanish: 'Militar', polish: 'Wojsko', braz_por: 'Militar' },
    'ui.ship_class.starbase': { english: 'Starbase', german: 'Sternenbasis', french: 'Base stellaire', russian: 'Звёздная база' , spanish: 'Base estelar', polish: 'Baza gwiezdna', braz_por: 'Base estelar' },
    'ui.ship_class.science': { english: 'Science', german: 'Wissenschaft', french: 'Science', russian: 'Научный' , spanish: 'Ciencia', polish: 'Nauka', braz_por: 'Ci\u00eancia' },
    'ui.ship_class.colonizer': { english: 'Colonizer', german: 'Kolonisator', french: 'Colonisateur', russian: 'Колонизатор' , spanish: 'Colonizador', polish: 'Kolonizator', braz_por: 'Colonizador' },
    'ui.ship_class.constructor': { english: 'Constructor', german: 'Konstruktor', french: 'Constructeur', russian: 'Конструктор' , spanish: 'Constructor', polish: 'Konstruktor', braz_por: 'Construtor' },
    'ui.ship_class.transport': { english: 'Transport', german: 'Transport', french: 'Transport', russian: 'Транспорт' , spanish: 'Transporte', polish: 'Transport', braz_por: 'Transporte' },
    'ui.ship_class.mining_station': { english: 'Mining Station', german: 'Minenstation', french: 'Station mini\u00e8re', russian: 'Горнодобывающая станция' , spanish: 'Estaci\u00f3n minera', polish: 'Stacja g\u00f3rnicza', braz_por: 'Esta\u00e7\u00e3o de minera\u00e7\u00e3o' },
    'ui.ship_class.research_station': { english: 'Research Station', german: 'Forschungsstation', french: 'Station de recherche', russian: 'Исследовательская станция' , spanish: 'Estaci\u00f3n de investigaci\u00f3n', polish: 'Stacja badawcza', braz_por: 'Esta\u00e7\u00e3o de pesquisa' },
    'ui.ship_class.observation_station': { english: 'Observation Station', german: 'Beobachtungsstation', french: 'Station d\'observation', russian: 'Наблюдательная станция' , spanish: 'Estaci\u00f3n de observaci\u00f3n', polish: 'Stacja obserwacyjna', braz_por: 'Esta\u00e7\u00e3o de observa\u00e7\u00e3o' },
    'ui.ship_class.military_station': { english: 'Military Station', german: 'Milit\u00e4rstation', french: 'Station militaire', russian: 'Военная станция' , spanish: 'Estaci\u00f3n militar', polish: 'Stacja wojskowa', braz_por: 'Esta\u00e7\u00e3o militar' },

    // Component type labels
    'ui.comp_type.weapon': { english: 'Weapon', german: 'Waffe', french: 'Arme', russian: 'Оружие' , spanish: 'Arma', polish: 'Bro\u0144', braz_por: 'Arma' },
    'ui.comp_type.utility': { english: 'Utility', german: 'Hilfssystem', french: 'Utilitaire', russian: 'Утилита' , spanish: 'Utilidad', polish: 'Wyposa\u017cenie', braz_por: 'Utilit\u00e1rio' },
    'ui.comp_type.strike_craft': { english: 'Strike Craft', german: 'Jagdfl\u00fcgler', french: 'Chasseur', russian: 'Штурмовик' , spanish: 'Naves de ataque', polish: 'My\u015bliwce', braz_por: 'Naves de ataque' },

    // Component size labels
    'ui.comp_size.small': { english: 'Small', german: 'Klein', french: 'Petit', russian: 'Малый' , spanish: 'Peque\u00f1o', polish: 'Ma\u0142y', braz_por: 'Pequeno' },
    'ui.comp_size.medium': { english: 'Medium', german: 'Mittel', french: 'Moyen', russian: 'Средний' , spanish: 'Mediano', polish: '\u015aredni', braz_por: 'M\u00e9dio' },
    'ui.comp_size.large': { english: 'Large', german: 'Gro\u00df', french: 'Grand', russian: 'Большой' , spanish: 'Grande', polish: 'Du\u017cy', braz_por: 'Grande' },
    'ui.comp_size.extra_large': { english: 'Extra Large', german: 'Sehr gro\u00df', french: 'Tr\u00e8s grand', russian: 'Очень большой' , spanish: 'Extragrande', polish: 'Bardzo du\u017cy', braz_por: 'Extragrande' },
    'ui.comp_size.titanic': { english: 'Titanic', german: 'Titanisch', french: 'Titanesque', russian: 'Титанический' , spanish: 'Tit\u00e1nico', polish: 'Tytaniczny', braz_por: 'Tit\u00e2nico' },
    'ui.comp_size.torpedo': { english: 'Torpedo', german: 'Torpedo', french: 'Torpedo', russian: 'Торпеда' , spanish: 'Torpedo', polish: 'Torpeda', braz_por: 'Torpedo' },
    'ui.comp_size.point_defence': { english: 'Point Defence', german: 'Punktverteidigung', french: 'D\u00e9fense ponctuelle', russian: 'Точечная оборона' , spanish: 'Defensa puntual', polish: 'Obrona punktowa', braz_por: 'Defesa pontual' },
    'ui.comp_size.aux': { english: 'Aux', german: 'Zusatz', french: 'Auxiliaire', russian: 'Вспомогательный' , spanish: 'Aux', polish: 'Pom.', braz_por: 'Aux' },
    'ui.comp_size.planet_killer': { english: 'Planet Killer', german: 'Planetenvernichter', french: 'D\u00e9vastateur de plan\u00e8te', russian: 'Уничтожитель планет' , spanish: 'Destructor de planetas', polish: 'Niszczyciel planet', braz_por: 'Destruidor de planetas' },

    // Building category labels
    'ui.bld_cat.amenity': { english: 'Amenity', german: 'Einrichtung', french: 'Commodit\u00e9', russian: 'Удобство' , spanish: 'Comodidad', polish: 'Udogodnienie', braz_por: 'Comodidade' },
    'ui.bld_cat.army': { english: 'Army', german: 'Armee', french: 'Arm\u00e9e', russian: 'Армия' , spanish: 'Ej\u00e9rcito', polish: 'Armia', braz_por: 'Ex\u00e9rcito' },
    'ui.bld_cat.government': { english: 'Government', german: 'Regierung', french: 'Gouvernement', russian: 'Правительство' , spanish: 'Gobierno', polish: 'Rz\u0105d', braz_por: 'Governo' },
    'ui.bld_cat.manufacturing': { english: 'Manufacturing', german: 'Fertigung', french: 'Fabrication', russian: 'Производство' , spanish: 'Manufactura', polish: 'Produkcja', braz_por: 'Manufatura' },
    'ui.bld_cat.pop_assembly': { english: 'Pop Assembly', german: 'Bevölkerungsmontageanl.', french: 'Assemblage de pop.', russian: 'Сборка пласта' , spanish: 'Ensamblaje de poblaci\u00f3n', polish: 'Monta\u017c populacji', braz_por: 'Montagem de popula\u00e7\u00e3o' },
    'ui.bld_cat.research': { english: 'Research', german: 'Forschung', french: 'Recherche', russian: 'Исследование' , spanish: 'Investigaci\u00f3n', polish: 'Badania', braz_por: 'Pesquisa' },
    'ui.bld_cat.resource': { english: 'Resource', german: 'Ressource', french: 'Ressource', russian: 'Ресурс' , spanish: 'Recurso', polish: 'Zas\u00f3b', braz_por: 'Recurso' },
    'ui.bld_cat.trade': { english: 'Trade', german: 'Handel', french: 'Commerce', russian: 'Торговля' , spanish: 'Comercio', polish: 'Handel', braz_por: 'Com\u00e9rcio' },
    'ui.bld_cat.unity': { english: 'Unity', german: 'Einheit', french: 'Unit\u00e9', russian: 'Единство' , spanish: 'Unidad', polish: 'Jedno\u015b\u0107', braz_por: 'Unidade' },

    // Quadrant labels (empires page)
    'ui.quadrant.all': { english: 'All', german: 'Alle', french: 'Tous', russian: 'Все' , spanish: 'Todos', polish: 'Wszystkie', braz_por: 'Todos' },
    'ui.quadrant.alpha': { english: '\u03b1 Alpha', german: '\u03b1 Alpha', french: '\u03b1 Alpha', russian: '\u03b1 Альфа' , spanish: '\u03b1 Alfa', polish: '\u03b1 Alfa', braz_por: '\u03b1 Alfa' },
    'ui.quadrant.beta': { english: '\u03b2 Beta', german: '\u03b2 Beta', french: '\u03b2 Beta', russian: '\u03b2 Бета' , spanish: '\u03b2 Beta', polish: '\u03b2 Beta', braz_por: '\u03b2 Beta' },
    'ui.quadrant.gamma': { english: '\u03b3 Gamma', german: '\u03b3 Gamma', french: '\u03b3 Gamma', russian: '\u03b3 Гамма' , spanish: '\u03b3 Gamma', polish: '\u03b3 Gamma', braz_por: '\u03b3 Gama' },
    'ui.quadrant.delta': { english: '\u03b4 Delta', german: '\u03b4 Delta', french: '\u03b4 Delta', russian: '\u03b4 Дельта' , spanish: '\u03b4 Delta', polish: '\u03b4 Delta', braz_por: '\u03b4 Delta' },
    'ui.quadrant.major': { english: '\u2605 Major', german: '\u2605 Major', french: '\u2605 Majeur', russian: '\u2605 Основные' , spanish: '\u2605 Mayor', polish: '\u2605 G\u0142\u00f3wne', braz_por: '\u2605 Maior' },
    'ui.quadrant.alt': { english: '\u25c8 Alt', german: '\u25c8 Alt', french: '\u25c8 Alt', russian: '\u25c8 Альт' , spanish: '\u25c8 Alt', polish: '\u25c8 Alt', braz_por: '\u25c8 Alt' },

    // Galaxy map legend & era labels
    'ui.galaxy.legend.alpha': { english: 'Alpha Quadrant', german: 'Alpha-Quadrant', french: 'Quadrant Alpha', russian: 'Альфа-квадрант' , spanish: 'Cuadrante Alfa', polish: 'Kwadrant Alfa', braz_por: 'Quadrante Alfa' },
    'ui.galaxy.legend.beta': { english: 'Beta Quadrant',  german: 'Beta-Quadrant',  french: 'Quadrant B\u00eata', russian: 'Бета-квадрант' , spanish: 'Cuadrante Beta', polish: 'Kwadrant Beta', braz_por: 'Quadrante Beta' },
    'ui.galaxy.legend.gamma': { english: 'Gamma Quadrant', german: 'Gamma-Quadrant', french: 'Quadrant Gamma', russian: 'Гамма-квадрант' , spanish: 'Cuadrante Gamma', polish: 'Kwadrant Gamma', braz_por: 'Quadrante Gama' },
    'ui.galaxy.legend.delta': { english: 'Delta Quadrant', german: 'Delta-Quadrant', french: 'Quadrant Delta', russian: 'Дельта-квадрант' , spanish: 'Cuadrante Delta', polish: 'Kwadrant Delta', braz_por: 'Quadrante Delta' },
    'ui.galaxy.legend.major': { english: 'Major Powers',   german: 'Gro\u00dfm\u00e4chte', french: 'Grandes puissances', russian: 'Крупные державы' , spanish: 'Grandes potencias', polish: 'Wielkie mocarstwa', braz_por: 'Grandes pot\u00eancias' },
    'ui.galaxy.legend.alt': { english: 'Alternate Timeline', german: 'Alternative Zeitlinie', french: 'Frise chronologique alternative', russian: 'Альтернативная временная линия' , spanish: 'L\u00ednea temporal alternativa', polish: 'Alternatywna linia czasu', braz_por: 'Linha temporal alternativa' },
    'ui.galaxy.era.classic': { english: 'Classic Era', german: 'Klassische Ära', french: 'Ère classique', russian: 'Классическая эпоха' , spanish: 'Era cl\u00e1sica', polish: 'Era klasyczna', braz_por: 'Era cl\u00e1ssica' },
    'ui.galaxy.era.tng': { english: 'TNG Era', german: 'TNG-Ära', french: 'Ère TNG', russian: 'Эпоха ТНГ' , spanish: 'Era TNG', polish: 'Era TNG', braz_por: 'Era TNG' },
    'ui.galaxy.reset': { english: '⌖ Reset View', german: '⌖ Ansicht zurücksetzen', french: '⌖ Réinitialiser la vue', russian: '⌖ Сбросить вид' , spanish: '\u2316 Restablecer vista', polish: '\u2316 Resetuj widok', braz_por: '\u2316 Redefinir vis\u00e3o' },

    // Filter by empire placeholder
    'ui.filter.empire':             { english: 'Empire', german: 'Reich', french: 'Empire', russian: 'Империя', spanish: 'Imperio', polish: 'Imperium', braz_por: 'Império' },
    'ui.filter.empire_placeholder': { english: 'Filter by empire...', german: 'Nach Reich filtern...', french: 'Filtrer par empire...', russian: 'Фильтр по империи...' , spanish: 'Filtrar por imperio...', polish: 'Filtruj wed\u0142ug imperium...', braz_por: 'Filtrar por imp\u00e9rio...' },

    // ==========================================
    // Search Placeholders
    // ==========================================
    'ui.search.hub': { english: 'Search all items...', german: 'Alle Eintr\u00e4ge durchsuchen...', french: 'Rechercher tous les \u00e9l\u00e9ments...', russian: 'Поиск всех элементов...' , spanish: 'Buscar todos los elementos...', polish: 'Szukaj wszystkich element\u00f3w...', braz_por: 'Buscar todos os itens...' },
    'ui.search.tech': { english: 'Search technologies...', german: 'Technologien durchsuchen...', french: 'Rechercher technologies...', russian: 'Поиск технологий...' , spanish: 'Buscar tecnolog\u00edas...', polish: 'Szukaj technologii...', braz_por: 'Buscar tecnologias...' },
    'ui.search.ships': { english: 'Search ships & components...', german: 'Schiffe & Komponenten durchsuchen...', french: 'Rechercher vaisseaux & composants...', russian: 'Поиск кораблей и компонентов...' , spanish: 'Buscar naves y componentes...', polish: 'Szukaj statk\u00f3w i komponent\u00f3w...', braz_por: 'Buscar naves e componentes...' },
    'ui.search.buildings': { english: 'Search buildings & districts...', german: 'Geb\u00e4ude & Bezirke durchsuchen...', french: 'Rechercher b\u00e2timents & districts...', russian: 'Поиск зданий и районов...' , spanish: 'Buscar edificios y distritos...', polish: 'Szukaj budynk\u00f3w i dzielnic...', braz_por: 'Buscar edif\u00edcios e distritos...' },
    'ui.search.traits': { english: 'Search traits, traditions & perks...', german: 'Eigenschaften, Traditionen & Vorteile durchsuchen...', french: 'Rechercher traits, traditions & atouts...', russian: 'Поиск черт, традиций и навыков...' , spanish: 'Buscar rasgos, tradiciones y ventajas...', polish: 'Szukaj cech, tradycji i atut\u00f3w...', braz_por: 'Buscar tra\u00e7os, tradi\u00e7\u00f5es e vantagens...' },
    'ui.search.governments': { english: 'Search governments, civics, policies...', german: 'Regierungen, B\u00fcrgerrechte, Richtlinien durchsuchen...', french: 'Rechercher gouvernements, civiques, politiques...', russian: 'Поиск правительств, общества, политик...' , spanish: 'Buscar gobiernos, doctrinas, pol\u00edticas...', polish: 'Szukaj rz\u0105d\u00f3w, ustroj\u00f3w, polityk...', braz_por: 'Buscar governos, doutrinas, pol\u00edticas...' },
    'ui.search.megastructures': { english: 'Search megastructures & relics...', german: 'Megastrukturen & Relikte durchsuchen...', french: 'Rechercher m\u00e9gastructures & reliques...', russian: 'Поиск мегаструктур и реликвий...' , spanish: 'Buscar megaestructuras y reliquias...', polish: 'Szukaj megastruktur i relikwii...', braz_por: 'Buscar megaestruturas e rel\u00edquias...' },
    'ui.search.anomalies': { english: 'Search anomalies & archaeology...', german: 'Anomalien & Arch\u00e4ologie durchsuchen...', french: 'Rechercher anomalies & arch\u00e9ologie...', russian: 'Поиск аномалий и археологии...' , spanish: 'Buscar anomal\u00edas y arqueolog\u00eda...', polish: 'Szukaj anomalii i archeologii...', braz_por: 'Buscar anomalias e arqueologia...' },
    'ui.search.empires': { english: 'Search empires & species...', german: 'Reiche & Spezies durchsuchen...', french: 'Rechercher empires & espèces...', russian: 'Поиск империй и видов...', spanish: 'Buscar imperios y especies...', polish: 'Szukaj imperiów i gatunków...', braz_por: 'Buscar impérios e espécies...' },
    'ui.search.exploration':  { english: 'Search anomalies, technologies, empires...', german: 'Anomalien, Technologien, Reiche durchsuchen...', french: 'Rechercher anomalies, technologies, empires...', russian: 'Поиск аномалий, технологий, империй...', spanish: 'Buscar anomalías, tecnologías, imperios...', polish: 'Szukaj anomalii, technologii, imperiów...', braz_por: 'Buscar anomalias, tecnologias, impérios...' },
    'ui.search.economy':      { english: 'Search buildings, jobs, megastructures...', german: 'Gebäude, Berufe, Megastrukturen durchsuchen...', french: 'Rechercher bâtiments, emplois, mégastructures...', russian: 'Поиск зданий, профессий, мегаструктур...', spanish: 'Buscar edificios, empleos, megaestructuras...', polish: 'Szukaj budynków, prac, megastruktur...', braz_por: 'Buscar edifícios, empregos, megaestruturas...' },
    'ui.search.events': { english: 'Search events... (id:, ns:, faction:)', german: 'Ereignisse durchsuchen... (id:, ns:, faction:)', french: 'Rechercher \u00e9v\u00e9nements... (id:, ns:, faction:)', russian: 'Поиск событий... (id:, ns:, faction:)' , spanish: 'Buscar eventos... (id:, ns:, faction:)', polish: 'Szukaj wydarze\u0144... (id:, ns:, faction:)', braz_por: 'Buscar eventos... (id:, ns:, faction:)' },

    // ==========================================
    // Detail Section Titles
    // ==========================================
    'ui.detail.detail': { english: 'Detail', german: 'Detail', french: 'Détail', russian: 'Подробности' , spanish: 'Detalle', polish: 'Szczeg\u00f3\u0142y', braz_por: 'Detalhe' },
    'ui.detail.stats': { english: 'Stats', german: 'Werte', french: 'Statistiques', russian: 'Характеристики' , spanish: 'Estad\u00edsticas', polish: 'Statystyki', braz_por: 'Estat\u00edsticas' },
    'ui.detail.prerequisites': { english: 'Prerequisites', german: 'Voraussetzungen', french: 'Prérequis', russian: 'Предусловия' , spanish: 'Requisitos previos', polish: 'Wymagania wst\u0119pne', braz_por: 'Pr\u00e9-requisitos' },
    'ui.detail.resources': { english: 'Resources', german: 'Ressourcen', french: 'Ressources', russian: 'Ресурсы' , spanish: 'Recursos', polish: 'Zasoby', braz_por: 'Recursos' },
    'ui.detail.modifiers': { english: 'Modifiers', german: 'Modifikatoren', french: 'Modificateurs', russian: 'Модификаторы' , spanish: 'Modificadores', polish: 'Modyfikatory', braz_por: 'Modificadores' },
    'ui.detail.modifier': { english: 'Modifier',  german: 'Modifikator',   french: 'Modificateur',  russian: 'Модификатор' , spanish: 'Modificador', polish: 'Modyfikator', braz_por: 'Modificador' },
    'ui.detail.conditions': { english: 'Conditions', german: 'Bedingungen', french: 'Conditions', russian: 'Условия' , spanish: 'Condiciones', polish: 'Warunki', braz_por: 'Condi\u00e7\u00f5es' },
    'ui.detail.on_spawn': { english: 'On Spawn', german: 'Beim Erscheinen', french: 'À l’apparition', russian: 'При появлении' , spanish: 'Al aparecer', polish: 'Przy pojawieniu', braz_por: 'Ao surgir' },
    'ui.detail.section_slots': { english: 'Section Slots', german: 'Sektionspl\u00e4tze', french: 'Emplacements de section', russian: 'Слоты секций' , spanish: 'Ranuras de secci\u00f3n', polish: 'Sloty sekcji', braz_por: 'Compartimentos de se\u00e7\u00e3o' },
    'ui.detail.tags': { english: 'Tags', german: 'Tags', french: 'Étiquettes', russian: 'Метки' , spanish: 'Etiquetas', polish: 'Znaczniki', braz_por: 'Etiquetas' },
    'ui.detail.description': { english: 'Description', german: 'Beschreibung', french: 'Description', russian: 'Описание' , spanish: 'Descripci\u00f3n', polish: 'Opis', braz_por: 'Descri\u00e7\u00e3o' },
    'ui.detail.opposites': { english: 'Opposites', german: 'Gegenteile', french: 'Opposés', russian: 'Противоположности' , spanish: 'Opuestos', polish: 'Przeciwie\u0144stwa', braz_por: 'Opostos' },
    'ui.detail.requirements': { english: 'Requirements', german: 'Anforderungen', french: 'Exigences', russian: 'Требования' , spanish: 'Requisitos', polish: 'Wymagania', braz_por: 'Requisitos' },
    'ui.detail.on_enabled': { english: 'On Enabled', german: 'Bei Aktivierung', french: 'À l’activation', russian: 'При активации' , spanish: 'Al activar', polish: 'Po w\u0142\u0105czeniu', braz_por: 'Ao ativar' },
    'ui.detail.tradition_swaps': { english: 'Tradition Swaps', german: 'Traditionstausch', french: 'Échanges de traditions', russian: 'Замены традиций' , spanish: 'Intercambios de tradici\u00f3n', polish: 'Zamiany tradycji', braz_por: 'Trocas de tradi\u00e7\u00e3o' },
    'ui.detail.upgrades_to': { english: 'Upgrades To', german: 'Ausbau zu', french: 'Amélioration vers', russian: 'Улучшается до' , spanish: 'Mejora a', polish: 'Ulepsza do', braz_por: 'Melhora para' },
    'ui.detail.potential': { english: 'Potential', german: 'Potenzial', french: 'Potentiel', russian: 'Потенциал' , spanish: 'Potencial', polish: 'Potencja\u0142', braz_por: 'Potencial' },
    'ui.detail.leader_possible': { english: 'Leader Requirements', german: 'Anf\u00fchreranforderungen', french: 'Exigences de chef', russian: 'Требования к лидеру' , spanish: 'Requisitos de l\u00edder', polish: 'Wymagania przyw\u00f3dcy', braz_por: 'Requisitos de l\u00edder' },
    'ui.detail.options': { english: 'Options', german: 'Optionen', french: 'Options', russian: 'Варианты' , spanish: 'Opciones', polish: 'Opcje', braz_por: 'Op\u00e7\u00f5es' },
    'ui.detail.weight': { english: 'Weight', german: 'Gewichtung', french: 'Poids', russian: 'Вес' , spanish: 'Peso', polish: 'Waga', braz_por: 'Peso' },
    'ui.detail.active_effect': { english: 'Active Effect', german: 'Aktiver Effekt', french: 'Effet actif', russian: 'Активный эффект' , spanish: 'Efecto activo', polish: 'Efekt aktywny', braz_por: 'Efeito ativo' },
    'ui.detail.possible': { english: 'Possible', german: 'M\u00f6glich', french: 'Possible', russian: 'Возможно' , spanish: 'Posible', polish: 'Mo\u017cliwe', braz_por: 'Poss\u00edvel' },
    'ui.detail.on_build_complete': { english: 'On Build Complete', german: 'Bei Fertigstellung', french: 'À la fin de construction', russian: 'По завершении строительства' , spanish: 'Al completar construcci\u00f3n', polish: 'Po uko\u0144czeniu budowy', braz_por: 'Ao concluir a constru\u00e7\u00e3o' },
    'ui.detail.success_outcomes': { english: 'Success Outcomes', german: 'Erfolgsergebnisse', french: 'Résultats réussis', russian: 'Успешные исходы' , spanish: 'Resultados de \u00e9xito', polish: 'Wyniki sukcesu', braz_por: 'Resultados de sucesso' },
    'ui.detail.spawn_chance': { english: 'Spawn Chance', german: 'Erscheinungschance', french: 'Chance d’apparition', russian: 'Шанс появления' , spanish: 'Probabilidad de aparici\u00f3n', polish: 'Szansa pojawienia', braz_por: 'Chance de surgimento' },
    'ui.detail.stages': { english: 'Stages', german: 'Stufen', french: 'Étapes', russian: 'Этапы' , spanish: 'Fases', polish: 'Etapy', braz_por: 'Fases' },
    'ui.detail.info': { english: 'Info', german: 'Info', french: 'Infos', russian: 'Инфо' , spanish: 'Informaci\u00f3n', polish: 'Informacje', braz_por: 'Informa\u00e7\u00f5es' },
    'ui.detail.ethics': { english: 'Ethics', german: 'Ethiken', french: 'Éthiques', russian: 'Этика' , spanish: '\u00c9ticas', polish: 'Etyki', braz_por: '\u00c9ticas' },
    'ui.detail.civics': { english: 'Civics', german: 'B\u00fcrgerrechte', french: 'Civiques', russian: 'Общественное устройство' , spanish: 'Doctrinas', polish: 'Ustroje', braz_por: 'Doutrinas' },
    'ui.detail.species': { english: 'Species', german: 'Spezies', french: 'Espèces', russian: 'Виды' , spanish: 'Especies', polish: 'Gatunki', braz_por: 'Esp\u00e9cies' },
    'ui.detail.ruler': { english: 'Ruler', german: 'Herrscher', french: 'Dirigeant', russian: 'Правитель' , spanish: 'Gobernante', polish: 'W\u0142adca', braz_por: 'Governante' },
    'ui.detail.portraits': { english: 'Portraits', german: 'Portr\u00e4ts', french: 'Portraits', russian: 'Портреты' , spanish: 'Retratos', polish: 'Portrety', braz_por: 'Retratos' },
    'ui.detail.drop_weight': { english: 'Drop Weight', german: 'Fallgewichtung', french: 'Poids de drop', russian: 'Вес выпадения' , spanish: 'Peso de aparici\u00f3n', polish: 'Waga wyst\u0105pienia', braz_por: 'Peso de ocorr\u00eancia' },
    'ui.detail.3d_model': { english: '3D Model', german: '3D-Modell', french: 'Modèle 3D', russian: '3D-модель' , spanish: 'Modelo 3D', polish: 'Model 3D', braz_por: 'Modelo 3D' },
    'ui.detail.required_traditions': { english: 'Required Traditions', german: 'Benötigte Traditionen', french: 'Traditions requises', russian: 'Нужные традиции' , spanish: 'Tradiciones requeridas', polish: 'Wymagane tradycje', braz_por: 'Tradi\u00e7\u00f5es necess\u00e1rias' },
    'ui.detail.min_perks': { english: 'Required Ascension Perks', german: 'Benötigte Ascension Perks', french: 'Atouts d’ascension requis', russian: 'Нужные навыки возвышения' , spanish: 'Ventajas de ascensi\u00f3n requeridas', polish: 'Wymagane atuty wniebowst\u0105pienia', braz_por: 'Vantagens de ascens\u00e3o necess\u00e1rias' },
    'ui.detail.required_flags': { english: 'Required Empire', german: 'Benötigtes Reich', french: 'Empire requis', russian: 'Нужная империя' , spanish: 'Imperio requerido', polish: 'Wymagane imperium', braz_por: 'Imp\u00e9rio necess\u00e1rio' },

    // ==========================================
    // Meta Labels
    // ==========================================
    'ui.meta.id': { english: 'ID', german: 'ID', french: 'ID', russian: 'ID' , spanish: 'ID', polish: 'ID', braz_por: 'ID' },
    'ui.meta.class': { english: 'Class', german: 'Klasse', french: 'Classe', russian: 'Класс' , spanish: 'Clase', polish: 'Klasa', braz_por: 'Classe' },
    'ui.meta.type': { english: 'Type', german: 'Typ', french: 'Type', russian: 'Тип' , spanish: 'Tipo', polish: 'Typ', braz_por: 'Tipo' },
    'ui.meta.size': { english: 'Size', german: 'Gr\u00f6\u00dfe', french: 'Taille', russian: 'Размер' , spanish: 'Tama\u00f1o', polish: 'Rozmiar', braz_por: 'Tamanho' },
    'ui.meta.file': { english: 'File', german: 'Datei', french: 'Fichier', russian: 'Файл' , spanish: 'Archivo', polish: 'Plik', braz_por: 'Arquivo' },
    'ui.meta.hp': { english: 'HP', german: 'TP', french: 'PV', russian: 'ЗД' , spanish: 'PS', polish: 'P\u017b', braz_por: 'PV' },
    'ui.meta.speed': { english: 'Speed', german: 'Geschwindigkeit', french: 'Vitesse', russian: 'Скорость' , spanish: 'Velocidad', polish: 'Pr\u0119dko\u015b\u0107', braz_por: 'Velocidade' },
    'ui.meta.build_time': { english: 'Build Time', german: 'Bauzeit', french: 'Temps de construction', russian: 'Время строительства' , spanish: 'Tiempo de construcci\u00f3n', polish: 'Czas budowy', braz_por: 'Tempo de constru\u00e7\u00e3o' },
    'ui.meta.power': { english: 'Power', german: 'Energie', french: 'Énergie', russian: 'Энергия' , spanish: 'Potencia', polish: 'Moc', braz_por: 'Pot\u00eancia' },
    'ui.meta.damage': { english: 'Damage', german: 'Schaden', french: 'Dégâts', russian: 'Урон' , spanish: 'Da\u00f1o', polish: 'Obra\u017cenia', braz_por: 'Dano' },
    'ui.meta.range': { english: 'Range', german: 'Reichweite', french: 'Portée', russian: 'Дальность' , spanish: 'Alcance', polish: 'Zasi\u0119g', braz_por: 'Alcance' },
    'ui.meta.accuracy': { english: 'Accuracy', german: 'Genauigkeit', french: 'Précision', russian: 'Точность' , spanish: 'Precisi\u00f3n', polish: 'Celno\u015b\u0107', braz_por: 'Precis\u00e3o' },
    'ui.meta.tracking': { english: 'Tracking', german: 'Zielverfolgung', french: 'Suivi', russian: 'Слежение' , spanish: 'Seguimiento', polish: '\u015aledzenie', braz_por: 'Rastreamento' },
    'ui.meta.category': { english: 'Category', german: 'Kategorie', french: 'Catégorie', russian: 'Категория' , spanish: 'Categor\u00eda', polish: 'Kategoria', braz_por: 'Categoria' },
    'ui.meta.rarity': { english: 'Rarity', german: 'Seltenheit', french: 'Rareté', russian: 'Редкость' , spanish: 'Rareza', polish: 'Rzadko\u015b\u0107', braz_por: 'Raridade' },
    'ui.meta.tier': { english: 'Tier', german: 'Stufe', french: 'Niveau', russian: 'Уровень' , spanish: 'Nivel', polish: 'Poziom', braz_por: 'N\u00edvel' },
    'ui.meta.tree': { english: 'Tree', german: 'Baum', french: 'Arbre', russian: 'Дерево' , spanish: '\u00c1rbol', polish: 'Drzewo', braz_por: '\u00c1rvore' },
    'ui.meta.role': { english: 'Role', german: 'Rolle', french: 'Rôle', russian: 'Роль' , spanish: 'Rol', polish: 'Rola', braz_por: 'Fun\u00e7\u00e3o' },
    'ui.meta.cost': { english: 'Cost', german: 'Kosten', french: 'Coût', russian: 'Стоимость' , spanish: 'Coste', polish: 'Koszt', braz_por: 'Custo' },
    'ui.meta.ruler': { english: 'Ruler', german: 'Herrscher', french: 'Dirigeant', russian: 'Правитель' , spanish: 'Gobernante', polish: 'W\u0142adca', braz_por: 'Governante' },
    'ui.meta.election': { english: 'Election', german: 'Wahl', french: 'Élection', russian: 'Выборы' , spanish: 'Elecci\u00f3n', polish: 'Wybory', braz_por: 'Elei\u00e7\u00e3o' },
    'ui.meta.duration': { english: 'Duration', german: 'Dauer', french: 'Durée', russian: 'Длительность' , spanish: 'Duraci\u00f3n', polish: 'Czas trwania', braz_por: 'Dura\u00e7\u00e3o' },
    'ui.meta.entity': { english: 'Entity', german: 'Entit\u00e4t', french: 'Entité', russian: 'Сущность' , spanish: 'Entidad', polish: 'Encja', braz_por: 'Entidade' },
    'ui.meta.upgrade_from': { english: 'Upgrade From', german: 'Ausbau von', french: 'Amélioration depuis', russian: 'Улучшается из' , spanish: 'Mejora desde', polish: 'Ulepszenie z', braz_por: 'Melhora de' },
    'ui.meta.sensor_range': { english: 'Sensor Range', german: 'Sensorreichweite', french: 'Portée du capteur', russian: 'Дальность сенсора' , spanish: 'Alcance de sensores', polish: 'Zasi\u0119g czujnik\u00f3w', braz_por: 'Alcance dos sensores' },
    'ui.meta.activation_duration': { english: 'Activation Duration', german: 'Aktivierungsdauer', french: 'Durée d’activation', russian: 'Длительность активации' , spanish: 'Duraci\u00f3n de activaci\u00f3n', polish: 'Czas aktywacji', braz_por: 'Dura\u00e7\u00e3o da ativa\u00e7\u00e3o' },
    'ui.meta.score': { english: 'Score', german: 'Punkte', french: 'Score', russian: 'Очки' , spanish: 'Puntuaci\u00f3n', polish: 'Wynik', braz_por: 'Pontua\u00e7\u00e3o' },
    'ui.meta.desc': { english: 'Desc', german: 'Beschr.', french: 'Desc', russian: 'Опис.' , spanish: 'Desc.', polish: 'Opis', braz_por: 'Desc.' },
    'ui.meta.level': { english: 'Level', german: 'Stufe', french: 'Niveau', russian: 'Уровень' , spanish: 'Nivel', polish: 'Poziom', braz_por: 'N\u00edvel' },
    'ui.meta.picture': { english: 'Picture', german: 'Bild', french: 'Image', russian: 'Изображение' , spanish: 'Imagen', polish: 'Obraz', braz_por: 'Imagem' },
    'ui.meta.max_once': { english: 'Max Once', german: 'Max. einmal', french: 'Maximum une fois', russian: 'Макс. один раз' , spanish: 'M\u00e1x. una vez', polish: 'Maks. raz', braz_por: 'M\u00e1x. uma vez' },
    'ui.meta.max_instances': { english: 'Max Instances', german: 'Max. Instanzen', french: 'Instances max.', russian: 'Макс. экземпляры' , spanish: 'Instancias m\u00e1x.', polish: 'Maks. instancji', braz_por: 'Inst\u00e2ncias m\u00e1x.' },
    'ui.meta.authority': { english: 'Authority', german: 'Autorit\u00e4t', french: 'Autorité', russian: 'Система власти' , spanish: 'Autoridad', polish: 'W\u0142adza', braz_por: 'Autoridade' },
    'ui.meta.government': { english: 'Government', german: 'Regierung', french: 'Gouvernement', russian: 'Правительство' , spanish: 'Gobierno', polish: 'Rz\u0105d', braz_por: 'Governo' },
    'ui.meta.origin': { english: 'Origin', german: 'Ursprung', french: 'Origine', russian: 'Происхождение' , spanish: 'Origen', polish: 'Pochodzenie', braz_por: 'Origem' },
    'ui.meta.ship_prefix': { english: 'Ship Prefix', german: 'Schiffspr\u00e4fix', french: 'Préfixe de vaisseau', russian: 'Префикс корабля' , spanish: 'Prefijo de nave', polish: 'Prefiks statku', braz_por: 'Prefixo da nave' },
    'ui.meta.culture': { english: 'Culture', german: 'Kultur', french: 'Culture', russian: 'Культура' , spanish: 'Cultura', polish: 'Kultura', braz_por: 'Cultura' },
    'ui.meta.homeworld': { english: 'Homeworld', german: 'Heimatwelt', french: 'Monde natal', russian: 'Родной мир' , spanish: 'Mundo natal', polish: '\u015awiat ojczysty', braz_por: 'Mundo natal' },
    'ui.meta.planet_class': { english: 'Planet Class', german: 'Planetenklasse', french: 'Classe planétaire', russian: 'Класс планеты' , spanish: 'Clase de planeta', polish: 'Klasa planety', braz_por: 'Classe de planeta' },
    'ui.meta.system': { english: 'System', german: 'System', french: 'Système', russian: 'Система' , spanish: 'Sistema', polish: 'System', braz_por: 'Sistema' },
    'ui.meta.archetype': { english: 'Archetype', german: 'Archetyp', french: 'Archétype', russian: 'Архетип' , spanish: 'Arquetipo', polish: 'Archetyp', braz_por: 'Arqu\u00e9tipo' },
    'ui.meta.uplifted_into': { english: 'Uplifted Into', german: 'Erhoben zu', french: 'Élevé en', russian: 'Возвышен до' , spanish: 'Elevado a', polish: 'Wyniesiony do', braz_por: 'Elevado a' },
    'ui.meta.gender': { english: 'Gender', german: 'Geschlecht', french: 'Genre', russian: 'Пол' , spanish: 'G\u00e9nero', polish: 'P\u0142e\u0107', braz_por: 'G\u00eanero' },
    'ui.meta.building_icon': { english: 'Building Icon', german: 'Geb\u00e4udesymbol', french: 'Icône de bâtiment', russian: 'Иконка здания' , spanish: 'Icono de edificio', polish: 'Ikona budynku', braz_por: '\u00cdcone de edif\u00edcio' },
    'ui.meta.condition': { english: 'Condition', german: 'Bedingung', french: 'Condition', russian: 'Условие' , spanish: 'Condici\u00f3n', polish: 'Warunek', braz_por: 'Condi\u00e7\u00e3o' },
    'ui.meta.capped_by_modifier': { english: 'Capped by Modifier', german: 'Begrenzt durch Modifikator', french: 'Limité par modificateur', russian: 'Ограничено модификатором' , spanish: 'Limitado por modificador', polish: 'Ograniczone modyfikatorem', braz_por: 'Limitado por modificador' },
    'ui.meta.null_deposit': { english: 'Null Deposit', german: 'Leer-Lagerst\u00e4tte', french: 'Dépôt vide', russian: 'Пустое месторождение' , spanish: 'Yacimiento nulo', polish: 'Puste z\u0142o\u017ce', braz_por: 'Dep\u00f3sito nulo' },
    'ui.meta.for_colonizable': { english: 'For Colonizable', german: 'F\u00fcr Kolonisierbare', french: 'Pour colonisable', russian: 'Для колонизируемых' , spanish: 'Para colonizables', polish: 'Dla nadaj\u0105cych si\u0119 do kolonizacji', braz_por: 'Para coloniz\u00e1veis' },
    'ui.meta.stages': { english: 'Stages', german: 'Stufen', french: 'Étapes', russian: 'Этапы' , spanish: 'Fases', polish: 'Etapy', braz_por: 'Fases' },
    'ui.meta.civic': { english: 'Civic', german: 'B\u00fcrgerrecht', french: 'Civique', russian: 'Общественное' , spanish: 'Doctrina', polish: 'Ustr\u00f3j', braz_por: 'Doutrina' },

    // ==========================================
    // Card Meta Prefixes
    // ==========================================
    'ui.card.tech': { english: 'Tech', german: 'Tech', french: 'Tech', russian: 'Тех' , spanish: 'Tecnolog\u00eda', polish: 'Technologia', braz_por: 'Tecnologia' },
    'ui.card.build': { english: 'Build', german: 'Bau', french: 'Construction', russian: 'Строительство' , spanish: 'Construir', polish: 'Buduj', braz_por: 'Construir' },
    'ui.card.from': { english: 'From', german: 'Von', french: 'De', russian: 'От' , spanish: 'De', polish: 'Od', braz_por: 'De' },
    'ui.card.score': { english: 'Score', german: 'Punkte', french: 'Score', russian: 'Очки' , spanish: 'Puntuaci\u00f3n', polish: 'Wynik', braz_por: 'Pontua\u00e7\u00e3o' },
    'ui.card.duration': { english: 'Duration', german: 'Dauer', french: 'Durée', russian: 'Длительность' , spanish: 'Duraci\u00f3n', polish: 'Czas trwania', braz_por: 'Dura\u00e7\u00e3o' },
    'ui.card.options': { english: 'options', german: 'Optionen', french: 'options', russian: 'варианты' , spanish: 'opciones', polish: 'opcje', braz_por: 'op\u00e7\u00f5es' },
    'ui.card.outcomes': { english: 'outcomes', german: 'Ergebnisse', french: 'résultats', russian: 'исходы' , spanish: 'resultados', polish: 'wyniki', braz_por: 'resultados' },
    'ui.card.stages': { english: 'stages', german: 'Stufen', french: 'étapes', russian: 'этапы' , spanish: 'fases', polish: 'etapy', braz_por: 'fases' },
    'ui.card.stage': { english: 'Stage',  german: 'Stufe',  french: 'Étape',  russian: 'Этап' , spanish: 'Fase', polish: 'Etap', braz_por: 'Fase' },
    'ui.card.ethics': { english: 'ethics', german: 'Ethiken', french: 'éthiques', russian: 'этика' , spanish: '\u00e9ticas', polish: 'etyki', braz_por: '\u00e9ticas' },

    // ==========================================
    // Badges
    // ==========================================
    'ui.badge.origin': { english: 'Origin', german: 'Ursprung', french: 'Origine', russian: 'Происхождение' , spanish: 'Origen', polish: 'Pochodzenie', braz_por: 'Origem' },
    'ui.badge.ambition': { english: 'Ambition', german: 'Ambition', french: 'Ambition', russian: 'Амбиция' , spanish: 'Ambici\u00f3n', polish: 'Ambicja', braz_por: 'Ambi\u00e7\u00e3o' },
    'ui.badge.unique': { english: 'Unique', german: 'Einzigartig', french: 'Unique', russian: 'Уникальное' , spanish: '\u00danico', polish: 'Unikalny', braz_por: '\u00danico' },
    'ui.badge.capital': { english: 'Capital', german: 'Hauptstadt', french: 'Capitale', russian: 'Столица' , spanish: 'Capital', polish: 'Stolica', braz_por: 'Capital' },
    'ui.badge.colonizable': { english: 'Colonizable', german: 'Kolonisierbar', french: 'Colonisable', russian: 'Колонизируемая' , spanish: 'Colonizable', polish: 'Mo\u017cliwa kolonizacja', braz_por: 'Coloniz\u00e1vel' },
    'ui.badge.has_heir': { english: 'Has Heir', german: 'Hat Erben', french: 'A un héritier', russian: 'Есть наследник' , spanish: 'Tiene heredero', polish: 'Ma nast\u0119pc\u0119', braz_por: 'Tem herdeiro' },
    'ui.badge.triggered_only': { english: 'triggered only', german: 'nur ausgel\u00f6st', french: 'déclenché uniquement', russian: 'только триггерное' , spanish: 'solo activado', polish: 'tylko wyzwalane', braz_por: 'apenas acionado' },
    'ui.badge.hidden': { english: 'hidden', german: 'versteckt', french: 'caché', russian: 'скрытое' , spanish: 'oculto', polish: 'ukryte', braz_por: 'oculto' },
    'ui.badge.required': { english: 'Required', german: 'Pflicht', french: 'Requis', russian: 'Обязательное' , spanish: 'Requerido', polish: 'Wymagane', braz_por: 'Necess\u00e1rio' },
    'ui.badge.fire_once': { english: 'fire once', german: 'einmalig', french: 'une seule fois', russian: 'один раз' , spanish: 'una sola vez', polish: 'jednorazowo', braz_por: 'uma \u00fanica vez' },
    'ui.badge.diplomatic': { english: 'diplomatic', german: 'diplomatisch', french: 'diplomatique', russian: 'дипломатическое' , spanish: 'diplom\u00e1tico', polish: 'dyplomatyczny', braz_por: 'diplom\u00e1tico' },

    // ==========================================
    // Hub Page
    // ==========================================
    'ui.hub.subtitle': { english: 'Comprehensive off-game reference for the STNH Stellaris mod', german: 'Umfassendes Off-Game-Nachschlagewerk f\u00fcr die STNH Stellaris-Mod', french: 'Référence complète hors-jeu pour le mod STNH Stellaris', russian: 'Полный внеигровой справочник по моду STNH для Stellaris' , spanish: 'Referencia completa fuera del juego para el mod STNH de Stellaris', polish: 'Kompleksowe \u017ar\u00f3d\u0142o informacji poza gr\u0105 dla moda STNH do Stellaris', braz_por: 'Refer\u00eancia completa fora do jogo para o mod STNH de Stellaris' },
    'ui.hub.total_items': { english: 'Total Items', german: 'Gesamtanzahl', french: 'Total d’éléments', russian: 'Всего элементов' , spanish: 'Elementos totales', polish: '\u0141\u0105czna liczba element\u00f3w', braz_por: 'Total de itens' },
    'ui.hub.last_update': { english: 'Last Update', german: 'Letztes Update', french: 'Dernière mise à jour', russian: 'Последнее обновление' , spanish: '\u00daltima actualizaci\u00f3n', polish: 'Ostatnia aktualizacja', braz_por: '\u00daltima atualiza\u00e7\u00e3o' },
    'ui.hub.desc_events': { english: 'Browse all events with full localisation in 7 languages.', german: 'Alle Ereignisse mit voller Lokalisierung in 7 Sprachen durchsuchen.', french: 'Parcourir tous les événements avec une localisation complète en 7 langues.', russian: 'Просмотр всех событий с полной локализацией на 7 языках.' , spanish: 'Explora todos los eventos con localizaci\u00f3n completa en 7 idiomas.', polish: 'Przegl\u0105daj wszystkie wydarzenia z pe\u0142n\u0105 lokalizacj\u0105 w 7 j\u0119zykach.', braz_por: 'Navegue por todos os eventos com localiza\u00e7\u00e3o completa em 7 idiomas.' },
    'ui.hub.desc_tech': { english: 'Interactive technology tree with prerequisites and unlocks.', german: 'Interaktiver Technologiebaum mit Voraussetzungen und Freischaltungen.', french: 'Arbre technologique interactif avec prérequis et déblocages.', russian: 'Интерактивное дерево технологий с предусловиями и открытиями.' , spanish: '\u00c1rbol tecnol\u00f3gico interactivo con requisitos y desbloqueos.', polish: 'Interaktywne drzewo technologii z wymaganiami i odblokowaniami.', braz_por: '\u00c1rvore tecnol\u00f3gica interativa com pr\u00e9-requisitos e desbloqueios.' },
    'ui.hub.desc_ships': { english: 'Ship classes, sizes, components, and faction-specific designs.', german: 'Schiffsklassen, Gr\u00f6\u00dfen, Komponenten und fraktionsspezifische Designs.', french: 'Classes de vaisseaux, tailles, composants et designs spécifiques aux factions.', russian: 'Классы, размеры, компоненты кораблей и дизайны фракций.' , spanish: 'Clases de naves, tama\u00f1os, componentes y dise\u00f1os espec\u00edficos de facci\u00f3n.', polish: 'Klasy statk\u00f3w, rozmiary, komponenty i projekty frakcyjne.', braz_por: 'Classes de naves, tamanhos, componentes e designs espec\u00edficos de fac\u00e7\u00e3o.' },
    'ui.hub.desc_buildings': { english: 'Planetary buildings, districts, and their production chains.', german: 'Planetare Geb\u00e4ude, Bezirke und ihre Produktionsketten.', french: 'Bâtiments planétaires, districts et leurs chaînes de production.', russian: 'Планетарные здания, районы и цепочки производства.' , spanish: 'Edificios planetarios, distritos y sus cadenas de producci\u00f3n.', polish: 'Budynki planetarne, dzielnice i ich \u0142a\u0144cuchy produkcyjne.', braz_por: 'Edif\u00edcios planet\u00e1rios, distritos e suas cadeias de produ\u00e7\u00e3o.' },
    'ui.hub.desc_traits': { english: 'Leader traits, traditions, ascension perks and their effects.', german: 'Anf\u00fchrereigenschaften, Traditionen, Aufstiegsvorteile und ihre Effekte.', french: 'Traits des chefs, traditions, atouts d’ascension et leurs effets.', russian: 'Черты лидеров, традиции, навыки возвышения и их эффекты.' , spanish: 'Rasgos de l\u00edder, tradiciones, ventajas de ascensi\u00f3n y sus efectos.', polish: 'Cechy przyw\u00f3dc\u00f3w, tradycje, atuty wniebowst\u0105pienia i ich efekty.', braz_por: 'Tra\u00e7os de l\u00edder, tradi\u00e7\u00f5es, vantagens de ascens\u00e3o e seus efeitos.' },
    'ui.hub.desc_governments': { english: 'Government types, civics, authorities, policies, and edicts.', german: 'Regierungsformen, B\u00fcrgerrechte, Autorit\u00e4ten, Richtlinien und Edikte.', french: 'Types de gouvernements, civiques, autorités, politiques et édits.', russian: 'Типы правительств, общественное устройство, системы власти, политики и указы.' , spanish: 'Tipos de gobierno, doctrinas, autoridades, pol\u00edticas y edictos.', polish: 'Typy rz\u0105d\u00f3w, ustroje, w\u0142adze, polityki i edykty.', braz_por: 'Tipos de governo, doutrinas, autoridades, pol\u00edticas e \u00e9ditos.' },
    'ui.hub.desc_megastructures': { english: 'Megastructure types, relics, build stages, and requirements.', german: 'Megastrukturtypen, Relikte, Baustufen und Anforderungen.', french: 'Types de mégastructures, reliques, étapes de construction et exigences.', russian: 'Типы мегаструктур, реликвии, стадии строительства и требования.' , spanish: 'Tipos de megaestructuras, reliquias, fases de construcci\u00f3n y requisitos.', polish: 'Typy megastruktur, relikwie, etapy budowy i wymagania.', braz_por: 'Tipos de megaestruturas, rel\u00edquias, etapas de constru\u00e7\u00e3o e requisitos.' },
    'ui.hub.desc_anomalies': { english: 'Anomaly categories, archaeological sites, outcomes, and events.', german: 'Anomaliekategorien, arch\u00e4ologische St\u00e4tten, Ergebnisse und Ereignisse.', french: 'Catégories d’anomalies, sites archéologiques, résultats et événements.', russian: 'Категории аномалий, археологические памятники, результаты и события.' , spanish: 'Categor\u00edas de anomal\u00edas, yacimientos arqueol\u00f3gicos, resultados y eventos.', polish: 'Kategorie anomalii, stanowiska archeologiczne, wyniki i wydarzenia.', braz_por: 'Categorias de anomalias, s\u00edtios arqueol\u00f3gicos, resultados e eventos.' },
    'ui.hub.desc_empires': { english: 'Prescripted empires, species classes, factions, and portraits.', german: 'Vordefinierte Reiche, Speziesklassen, Fraktionen und Portr\u00e4ts.', french: 'Empires prédéfinis, classes d’espèces, factions et portraits.', russian: 'Преднастроенные империи, классы видов, фракции и портреты.' , spanish: 'Imperios predefinidos, clases de especies, facciones y retratos.', polish: 'Predefiniowane imperia, klasy gatunk\u00f3w, frakcje i portrety.', braz_por: 'Imp\u00e9rios predefinidos, classes de esp\u00e9cies, fac\u00e7\u00f5es e retratos.' },
    'ui.hub.desc_economy': { english: 'Pop jobs, deposits, resource production, and economic chains.', german: 'Pop-Berufe, Lagerst\u00e4tten, Ressourcenproduktion und Wirtschaftsketten.', french: 'Emplois de population, d\u00e9p\u00f4ts, production de ressources et cha\u00eenes \u00e9conomiques.', russian: '\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u0438 \u043f\u043e\u043f\u0443\u043b\u044f\u0446\u0438\u0438, \u043c\u0435\u0441\u0442\u043e\u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f, \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u043e \u0440\u0435\u0441\u0443\u0440\u0441\u043e\u0432 \u0438 \u044d\u043a\u043e\u043d\u043e\u043c\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0446\u0435\u043f\u043e\u0447\u043a\u0438.' , spanish: 'Empleos de poblaci\u00f3n, yacimientos, producci\u00f3n de recursos y cadenas econ\u00f3micas.', polish: 'Prace populacji, z\u0142o\u017ca, produkcja zasob\u00f3w i \u0142a\u0144cuchy gospodarcze.', braz_por: 'Empregos de popula\u00e7\u00e3o, dep\u00f3sitos, produ\u00e7\u00e3o de recursos e cadeias econ\u00f4micas.' },
    'ui.hub.blog_title':       { english: 'STNH Blog', german: 'STNH Blog', french: 'Blog STNH', spanish: 'Blog STNH', russian: '\u0411\u043b\u043e\u0433 STNH', polish: 'Blog STNH', braz_por: 'Blog STNH' },
    'ui.hub.blog_desc':        { english: 'News, dev updates and stories from the Star Trek: New Horizons team.', german: 'News, Dev-Updates und Geschichten aus dem Star Trek: New Horizons Team.', french: 'Actualit\u00e9s, mises \u00e0 jour et histoires de l\'\u00e9quipe Star Trek: New Horizons.', spanish: 'Noticias, actualizaciones de desarrollo e historias del equipo Star Trek: New Horizons.', russian: '\u041d\u043e\u0432\u043e\u0441\u0442\u0438, \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u0438 \u0438\u0441\u0442\u043e\u0440\u0438\u0438 \u043e\u0442 \u043a\u043e\u043c\u0430\u043d\u0434\u044b Star Trek: New Horizons.', polish: 'Wiadomo\u015bci, aktualizacje i historie zespo\u0142u Star Trek: New Horizons.', braz_por: 'Not\u00edcias, atualiza\u00e7\u00f5es e hist\u00f3rias da equipe Star Trek: New Horizons.' },
    'ui.hub.blog_cta':         { english: 'Visit the blog \u2192', german: 'Zum Blog \u2192', french: 'Visiter le blog \u2192', spanish: 'Visitar el blog \u2192', russian: '\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u0432 \u0431\u043b\u043e\u0433 \u2192', polish: 'Odwied\u017a blog \u2192', braz_por: 'Visitar o blog \u2192' },
    'ui.hub.analyzer_title':   { english: 'STNH Log Analyzer', german: 'STNH Log Analyzer', french: 'Analyseur de logs STNH', spanish: 'Analizador de registros STNH', russian: '\u0410\u043d\u0430\u043b\u0438\u0437\u0430\u0442\u043e\u0440 \u043b\u043e\u0433\u043e\u0432 STNH', polish: 'Analizator log\u00f3w STNH', braz_por: 'Analisador de logs STNH' },
    'ui.hub.analyzer_desc':    { english: 'Upload your savegame logs and analyze your empire\'s progress, fleets, and economy.', german: 'Lade deine Savegame-Logs hoch und analysiere Fortschritt, Flotten und Wirtschaft deines Reichs.', french: 'T\u00e9l\u00e9versez vos logs de sauvegarde et analysez la progression, les flottes et l\'\u00e9conomie de votre empire.', spanish: 'Sube los registros de tu partida y analiza el progreso, las flotas y la econom\u00eda de tu imperio.', russian: '\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u0435 \u043b\u043e\u0433\u0438 \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0438 \u043f\u0440\u043e\u0430\u043d\u0430\u043b\u0438\u0437\u0438\u0440\u0443\u0439\u0442\u0435 \u043f\u0440\u043e\u0433\u0440\u0435\u0441\u0441, \u0444\u043b\u043e\u0442\u044b \u0438 \u044d\u043a\u043e\u043d\u043e\u043c\u0438\u043a\u0443 \u0432\u0430\u0448\u0435\u0439 \u0438\u043c\u043f\u0435\u0440\u0438\u0438.', polish: 'Prze\u015blij logi zapis\u00f3w gry i przeanalizuj post\u0119py, floty i gospodark\u0119 swojego imperium.', braz_por: 'Envie os logs do seu savegame e analise o progresso, as frotas e a economia do seu imp\u00e9rio.' },
    'ui.hub.analyzer_cta':     { english: 'Open the analyzer \u2192', german: 'Zum Analyzer \u2192', french: 'Ouvrir l\'analyseur \u2192', spanish: 'Abrir el analizador \u2192', russian: '\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u0430\u043d\u0430\u043b\u0438\u0437\u0430\u0442\u043e\u0440 \u2192', polish: 'Otw\u00f3rz analizator \u2192', braz_por: 'Abrir o analisador \u2192' },

    // ==========================================
    // Event Detail Specific
    // ==========================================
    'ui.event.description': { english: 'Description', german: 'Beschreibung', french: 'Description', russian: 'Описание' , spanish: 'Descripci\u00f3n', polish: 'Opis', braz_por: 'Descri\u00e7\u00e3o' },
    'ui.event.condition': { english: 'Condition', german: 'Bedingung', french: 'Condition', russian: 'Условие' , spanish: 'Condici\u00f3n', polish: 'Warunek', braz_por: 'Condi\u00e7\u00e3o' },
    'ui.event.trigger_conditions': { english: 'Trigger Conditions', german: 'Ausl\u00f6sebedingungen', french: 'Conditions de déclenchement', russian: 'Условия триггера' , spanish: 'Condiciones de activaci\u00f3n', polish: 'Warunki wyzwolenia', braz_por: 'Condi\u00e7\u00f5es de ativa\u00e7\u00e3o' },
    'ui.event.immediate_effects': { english: 'Immediate Effects', german: 'Sofortige Effekte', french: 'Effets immédiats', russian: 'Немедленные эффекты' , spanish: 'Efectos inmediatos', polish: 'Efekty natychmiastowe', braz_por: 'Efeitos imediatos' },
    'ui.event.options': { english: 'Options', german: 'Optionen', french: 'Options', russian: 'Варианты' , spanish: 'Opciones', polish: 'Opcje', braz_por: 'Op\u00e7\u00f5es' },
    'ui.event.after_effects': { english: 'After Effects', german: 'Nachfolgende Effekte', french: 'Effets ultérieurs', russian: 'Последующие эффекты' , spanish: 'Efectos posteriores', polish: 'Efekty nast\u0119pcze', braz_por: 'Efeitos posteriores' },
    'ui.event.mtth': { english: 'Mean Time to Happen', german: 'Durchschnittliche Ausl\u00f6sezeit', french: 'Temps moyen d’occurrence', russian: 'Среднее время до срабатывания' , spanish: 'Tiempo medio hasta ocurrir', polish: '\u015aredni czas do wyst\u0105pienia', braz_por: 'Tempo m\u00e9dio at\u00e9 ocorrer' },
    'ui.event.on_actions': { english: 'Triggered by On-Actions', german: 'Ausgel\u00f6st durch On-Actions', french: 'Déclenché par des actions', russian: 'Триггерится действиями' , spanish: 'Activado por On-Actions', polish: 'Wyzwolone przez On-Actions', braz_por: 'Acionado por On-Actions' },
    'ui.event.triggered_by': { english: 'Triggered By', german: 'Ausgel\u00f6st von', french: 'Déclenché par', russian: 'Триггерится' , spanish: 'Activado por', polish: 'Wyzwolone przez', braz_por: 'Acionado por' },
    'ui.event.triggers': { english: 'Triggers', german: 'L\u00f6st aus', french: 'Déclenche', russian: 'Запускает' , spanish: 'Activadores', polish: 'Wyzwalacze', braz_por: 'Gatilhos' },
    'ui.event.requires': { english: 'Requires', german: 'Erfordert', french: 'Nécessite', russian: 'Требует' , spanish: 'Requiere', polish: 'Wymaga', braz_por: 'Requer' },
    'ui.event.shows_if': { english: 'Shows if', german: 'Zeigt wenn', french: 'Affiché si', russian: 'Показывается если' , spanish: 'Se muestra si', polish: 'Pokazuje si\u0119, je\u015bli', braz_por: 'Mostra-se se' },
    'ui.event.effects': { english: 'Effects', german: 'Effekte', french: 'Effets', russian: 'Эффекты' , spanish: 'Efectos', polish: 'Efekty', braz_por: 'Efeitos' },
    'ui.event.event_detail': { english: 'Event Detail', german: 'Ereignisdetail', french: 'Détail de l’événement', russian: 'Подробности события' , spanish: 'Detalle del evento', polish: 'Szczeg\u00f3\u0142y wydarzenia', braz_por: 'Detalhe do evento' },
    'ui.event.event_chain': { english: 'Event Chain', german: 'Ereigniskette', french: 'Chaîne d’événements', russian: 'Цепочка событий' , spanish: 'Cadena de eventos', polish: '\u0141a\u0144cuch wydarze\u0144', braz_por: 'Cadeia de eventos' },
    'ui.event.namespaces': { english: 'Namespaces', german: 'Namensr\u00e4ume', french: 'Espaces de noms', russian: 'Пространства имён' , spanish: 'Espacios de nombres', polish: 'Przestrzenie nazw', braz_por: 'Namespaces' },

    // ==========================================
    // Type Labels (Global Search)
    // ==========================================
    'ui.type.event': { english: 'Event', german: 'Ereignis', french: 'Événement', russian: 'Событие' , spanish: 'Evento', polish: 'Wydarzenie', braz_por: 'Evento' },
    'ui.type.ship': { english: 'Ship', german: 'Schiff', french: 'Vaisseau', russian: 'Корабль' , spanish: 'Nave', polish: 'Statek', braz_por: 'Nave' },
    'ui.type.component': { english: 'Component', german: 'Komponente', french: 'Composant', russian: 'Компонент' , spanish: 'Componente', polish: 'Komponent', braz_por: 'Componente' },
    'ui.type.building': { english: 'Building', german: 'Geb\u00e4ude', french: 'Bâtiment', russian: 'Здание' , spanish: 'Edificio', polish: 'Budynek', braz_por: 'Edif\u00edcio' },
    'ui.type.district': { english: 'District', german: 'Bezirk', french: 'District', russian: 'Район' , spanish: 'Distrito', polish: 'Dzielnica', braz_por: 'Distrito' },
    'ui.type.trait': { english: 'Trait', german: 'Eigenschaft', french: 'Trait', russian: 'Черта' , spanish: 'Rasgo', polish: 'Cecha', braz_por: 'Tra\u00e7o' },
    'ui.type.tradition': { english: 'Tradition', german: 'Tradition', french: 'Tradition', russian: 'Традиция' , spanish: 'Tradici\u00f3n', polish: 'Tradycja', braz_por: 'Tradi\u00e7\u00e3o' },
    'ui.type.ascension_perk': { english: 'Ascension Perk', german: 'Aufstiegsvorteil', french: 'Atout d’ascension', russian: 'Навык возвышения' , spanish: 'Ventaja de ascensi\u00f3n', polish: 'Atut wniebowst\u0105pienia', braz_por: 'Vantagem de ascens\u00e3o' },
    'ui.type.government': { english: 'Government', german: 'Regierung', french: 'Gouvernement', russian: 'Правительство' , spanish: 'Gobierno', polish: 'Rz\u0105d', braz_por: 'Governo' },
    'ui.type.civic': { english: 'Civic', german: 'B\u00fcrgerrecht', french: 'Civique', russian: 'Общественное' , spanish: 'Doctrina', polish: 'Ustr\u00f3j', braz_por: 'Doutrina' },
    'ui.type.authority': { english: 'Authority', german: 'Autorit\u00e4t', french: 'Autorité', russian: 'Система власти' , spanish: 'Autoridad', polish: 'W\u0142adza', braz_por: 'Autoridade' },
    'ui.type.policy': { english: 'Policy', german: 'Richtlinie', french: 'Politique', russian: 'Политика' , spanish: 'Pol\u00edtica', polish: 'Polityka', braz_por: 'Pol\u00edtica' },
    'ui.type.edict': { english: 'Edict', german: 'Edikt', french: 'Édit', russian: 'Указ' , spanish: 'Edicto', polish: 'Edykt', braz_por: '\u00c9dito' },
    'ui.type.megastructure': { english: 'Megastructure', german: 'Megastruktur', french: 'Mégastructure', russian: 'Мегаструктура' , spanish: 'Megaestructura', polish: 'Megastruktura', braz_por: 'Megaestrutura' },
    'ui.type.relic': { english: 'Relic', german: 'Relikt', french: 'Relique', russian: 'Реликвия' , spanish: 'Reliquia', polish: 'Relikwia', braz_por: 'Rel\u00edquia' },
    'ui.type.anomaly': { english: 'Anomaly', german: 'Anomalie', french: 'Anomalie', russian: 'Аномалия' , spanish: 'Anomal\u00eda', polish: 'Anomalia', braz_por: 'Anomalia' },
    'ui.type.archaeology': { english: 'Archaeology', german: 'Arch\u00e4ologie', french: 'Archéologie', russian: 'Археология' , spanish: 'Arqueolog\u00eda', polish: 'Archeologia', braz_por: 'Arqueologia' },
    'ui.type.empire': { english: 'Empire', german: 'Reich', french: 'Empire', russian: 'Империя' , spanish: 'Imperio', polish: 'Imperium', braz_por: 'Imp\u00e9rio' },
    'ui.type.species': { english: 'Species', german: 'Spezies', french: 'Espèces', russian: 'Вид' , spanish: 'Especies', polish: 'Gatunki', braz_por: 'Esp\u00e9cies' },
    'ui.type.job': { english: 'Job', german: 'Beruf', french: 'Emploi', russian: 'Профессия' , spanish: 'Empleo', polish: 'Praca', braz_por: 'Emprego' },
    'ui.type.deposit': { english: 'Deposit', german: 'Lagerst\u00e4tte', french: 'Dépôt', russian: 'Месторождение' , spanish: 'Yacimiento', polish: 'Z\u0142o\u017ce', braz_por: 'Dep\u00f3sito' },
    'ui.type.resource': { english: 'Resource', german: 'Ressource', french: 'Ressource', russian: 'Ресурс' , spanish: 'Recurso', polish: 'Zas\u00f3b', braz_por: 'Recurso' },
    'ui.type.councilor': { english: 'Councilor', german: 'Ratsmitglied', french: 'Conseiller', russian: 'Советник' , spanish: 'Consejero', polish: 'Radny', braz_por: 'Conselheiro' },
    'ui.type.technology': { english: 'Technology', german: 'Technologie', french: 'Technologie', russian: 'Технология' , spanish: 'Tecnolog\u00eda', polish: 'Technologia', braz_por: 'Tecnologia' },

    // ==========================================
    // Loading / Empty / Error States
    // ==========================================
    'ui.loading.ships': { english: 'Loading ship data', german: 'Lade Schiffsdaten', french: 'Chargement des données de vaisseaux', russian: 'Загрузка данных кораблей' , spanish: 'Cargando datos de naves', polish: 'Wczytywanie danych statk\u00f3w', braz_por: 'Carregando dados de naves' },
    'ui.loading.buildings': { english: 'Loading building data', german: 'Lade Geb\u00e4udedaten', french: 'Chargement des données de bâtiments', russian: 'Загрузка данных зданий' , spanish: 'Cargando datos de edificios', polish: 'Wczytywanie danych budynk\u00f3w', braz_por: 'Carregando dados de edif\u00edcios' },
    'ui.loading.traits': { english: 'Loading trait data', german: 'Lade Eigenschaftsdaten', french: 'Chargement des données de traits', russian: 'Загрузка данных черт' , spanish: 'Cargando datos de rasgos', polish: 'Wczytywanie danych cech', braz_por: 'Carregando dados de tra\u00e7os' },
    'ui.loading.governments': { english: 'Loading government data', german: 'Lade Regierungsdaten', french: 'Chargement des données de gouvernements', russian: 'Загрузка данных правительств' , spanish: 'Cargando datos de gobiernos', polish: 'Wczytywanie danych rz\u0105d\u00f3w', braz_por: 'Carregando dados de governos' },
    'ui.loading.megastructures': { english: 'Loading megastructure data', german: 'Lade Megastrukturdaten', french: 'Chargement des données de mégastructures', russian: 'Загрузка данных мегаструктур' , spanish: 'Cargando datos de megaestructuras', polish: 'Wczytywanie danych megastruktur', braz_por: 'Carregando dados de megaestruturas' },
    'ui.loading.anomalies': { english: 'Loading anomaly data', german: 'Lade Anomaliedaten', french: 'Chargement des données d’anomalies', russian: 'Загрузка данных аномалий' , spanish: 'Cargando datos de anomal\u00edas', polish: 'Wczytywanie danych anomalii', braz_por: 'Carregando dados de anomalias' },
    'ui.loading.empires': { english: 'Loading empire data', german: 'Lade Reichsdaten', french: 'Chargement des données d’empires', russian: 'Загрузка данных империй' , spanish: 'Cargando datos de imperios', polish: 'Wczytywanie danych imperi\u00f3w', braz_por: 'Carregando dados de imp\u00e9rios' },
    'ui.loading.economy': { english: 'Loading economy data', german: 'Lade Wirtschaftsdaten', french: 'Économie en chargement', russian: 'Загрузка экономических данных' , spanish: 'Cargando datos de econom\u00eda', polish: 'Wczytywanie danych gospodarki', braz_por: 'Carregando dados de economia' },
    'ui.loading.events': { english: 'Loading event data', german: 'Lade Ereignisdaten', french: 'Chargement des données d’événements', russian: 'Загрузка данных событий' , spanish: 'Cargando datos de eventos', polish: 'Wczytywanie danych wydarze\u0144', braz_por: 'Carregando dados de eventos' },
    'ui.loading.generic': { english: 'Loading...', german: 'Laden...', french: 'Chargement…', russian: 'Загрузка…' , spanish: 'Cargando...', polish: 'Wczytywanie...', braz_por: 'Carregando...' },
    'ui.loading.event_details': { english: 'Loading event details', german: 'Lade Ereignisdetails', french: 'Chargement des détails de l’événement', russian: 'Загрузка подробностей события' , spanish: 'Cargando detalles del evento', polish: 'Wczytywanie szczeg\u00f3\u0142\u00f3w wydarzenia', braz_por: 'Carregando detalhes do evento' },

    'ui.empty.no_items': { english: 'No items found', german: 'Keine Eintr\u00e4ge gefunden', french: 'Aucun élément trouvé', russian: 'Элементы не найдены' , spanish: 'No se encontraron elementos', polish: 'Nie znaleziono element\u00f3w', braz_por: 'Nenhum item encontrado' },
    'ui.empty.no_events': { english: 'No events found', german: 'Keine Ereignisse gefunden', french: 'Aucun événement trouvé', russian: 'События не найдены' , spanish: 'No se encontraron eventos', polish: 'Nie znaleziono wydarze\u0144', braz_por: 'Nenhum evento encontrado' },
    'ui.empty.no_results': { english: 'No results found', german: 'Keine Ergebnisse gefunden', french: 'Aucun résultat trouvé', russian: 'Результаты не найдены' , spanish: 'No se encontraron resultados', polish: 'Nie znaleziono wynik\u00f3w', braz_por: 'Nenhum resultado encontrado' },
    'ui.empty.no_results_any': { english: 'No results found across any module.', german: 'Keine Ergebnisse in allen Modulen gefunden.', french: 'Aucun résultat dans aucun module.', russian: 'Результаты не найдены ни в одном модуле.' , spanish: 'No se encontraron resultados en ning\u00fan m\u00f3dulo.', polish: 'Nie znaleziono wynik\u00f3w w \u017cadnym module.', braz_por: 'Nenhum resultado encontrado em nenhum m\u00f3dulo.' },
    'ui.empty.event_not_found': { english: 'Event not found in detail data', german: 'Ereignis nicht in Detaildaten gefunden', french: 'L’événement est introuvable dans les données de détail', russian: 'Событие не найдено в детальных данных' , spanish: 'Evento no encontrado en los datos detallados', polish: 'Nie znaleziono wydarzenia w danych szczeg\u00f3\u0142owych', braz_por: 'Evento n\u00e3o encontrado nos dados detalhados' },
    'ui.empty.other_namespaces': { english: 'Other namespaces', german: 'Andere Namensr\u00e4ume', french: 'Autres espaces de noms', russian: 'Другие пространства имён' , spanish: 'Otros espacios de nombres', polish: 'Inne przestrzenie nazw', braz_por: 'Outros namespaces' },

    'ui.error.load_failed': { english: 'Failed to load data', german: 'Daten konnten nicht geladen werden', french: 'Impossible de charger les données', russian: 'Не удалось загрузить данные' , spanish: 'Error al cargar los datos', polish: 'Nie uda\u0142o si\u0119 wczyta\u0107 danych', braz_por: 'Falha ao carregar os dados' },
    'ui.error.model_load_failed': { english: 'Could not load 3D model', german: '3D-Modell konnte nicht geladen werden', french: 'Impossible de charger le modèle 3D', russian: 'Не удалось загрузить 3D-модель' , spanish: 'No se pudo cargar el modelo 3D', polish: 'Nie uda\u0142o si\u0119 wczyta\u0107 modelu 3D', braz_por: 'N\u00e3o foi poss\u00edvel carregar o modelo 3D' },

    // ==========================================
    // Search UI (Hub)
    // ==========================================
    'ui.search.matches': { english: 'match', german: 'Treffer', french: 'correspondance', russian: 'совпадение' , spanish: 'coincidencia', polish: 'dopasowanie', braz_por: 'correspond\u00eancia' },
    'ui.search.matches_plural': { english: 'matches', german: 'Treffer', french: 'correspondances', russian: 'совпадения' , spanish: 'coincidencias', polish: 'dopasowania', braz_por: 'correspond\u00eancias' },
    'ui.search.press_enter': { english: 'press Enter for full results', german: 'Enter f\u00fcr alle Ergebnisse dr\u00fccken', french: 'appuyez sur Entrée pour les résultats complets', russian: 'нажмите Enter для полных результатов' , spanish: 'pulsa Enter para ver todos los resultados', polish: 'naci\u015bnij Enter, aby zobaczy\u0107 pe\u0142ne wyniki', braz_por: 'pressione Enter para ver todos os resultados' },
    'ui.search.more': { english: 'more', german: 'mehr', french: 'plus', russian: 'ещё' , spanish: 'm\u00e1s', polish: 'wi\u0119cej', braz_por: 'mais' },
    'ui.search.back': { english: 'Back', german: 'Zur\u00fcck', french: 'Retour', russian: 'Назад' , spanish: 'Atr\u00e1s', polish: 'Wstecz', braz_por: 'Voltar' },
    'ui.search.all': { english: 'All', german: 'Alle', french: 'Tous', russian: 'Все' , spanish: 'Todos', polish: 'Wszystkie', braz_por: 'Todos' },
    'ui.search.results_for': { english: 'results for', german: 'Ergebnisse f\u00fcr', french: 'résultats pour', russian: 'результаты по' , spanish: 'resultados para', polish: 'wyniki dla', braz_por: 'resultados para' },
    'ui.search.result': { english: 'result', german: 'Ergebnis', french: 'résultat', russian: 'результат' , spanish: 'resultado', polish: 'wynik', braz_por: 'resultado' },
    'ui.search.results': { english: 'results', german: 'Ergebnisse', french: 'résultats', russian: 'результаты' , spanish: 'resultados', polish: 'wyniki', braz_por: 'resultados' },
    'ui.search.show_more':     { english: 'Show more', german: 'Mehr anzeigen', french: 'Afficher plus', spanish: 'Mostrar más', russian: 'Показать ещё', polish: 'Pokaż więcej', braz_por: 'Mostrar mais' },
    'ui.search.also_searching': { english: 'also searching', german: 'sucht auch nach', french: 'recherche également', russian: 'также ищет' , spanish: 'tambi\u00e9n busca', polish: 'szuka tak\u017ce', braz_por: 'tamb\u00e9m busca' },
    'ui.search.global_results':{ english: 'Cross-module results', german: 'Modul\u00fcbergreifende Ergebnisse', french: 'R\u00e9sultats inter-modules', spanish: 'Resultados multi-m\u00f3dulo', russian: '\u041c\u0435\u0436\u043c\u043e\u0434\u0443\u043b\u044c\u043d\u044b\u0435 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b', polish: 'Wyniki mi\u0119dzymodu\u0142owe', braz_por: 'Resultados entre m\u00f3dulos' },
    'ui.search.global':        { english: 'Search all wiki...', german: 'Gesamtes Wiki durchsuchen...', french: 'Rechercher dans tout le wiki...', spanish: 'Buscar en toda la wiki...', russian: '\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0432\u0441\u0435\u0439 \u0432\u0438\u043a\u0438...', polish: 'Szukaj w ca\u0142ej wiki...', braz_por: 'Pesquisar em toda a wiki...' },
    'ui.search.global_off': { english: 'Global search (click to enable)', german: 'Globale Suche (klicken zum Aktivieren)', french: 'Recherche globale (cliquer pour activer)', russian: 'Глобальный поиск (нажмите для включения)' , spanish: 'B\u00fasqueda global (clic para activar)', polish: 'Wyszukiwanie globalne (kliknij, aby w\u0142\u0105czy\u0107)', braz_por: 'Busca global (clique para ativar)' },
    'ui.search.global_on': { english: 'Global search active (click to disable)', german: 'Globale Suche aktiv (klicken zum Deaktivieren)', french: 'Recherche globale active (cliquer pour désactiver)', russian: 'Глобальный поиск активен (нажмите для отключения)' , spanish: 'B\u00fasqueda global activa (clic para desactivar)', polish: 'Wyszukiwanie globalne aktywne (kliknij, aby wy\u0142\u0105czy\u0107)', braz_por: 'Busca global ativa (clique para desativar)' },
    'ui.search.global_label': { english: 'Global Search', german: 'Globale Suche', french: 'Recherche globale', russian: 'Глобальный поиск' , spanish: 'B\u00fasqueda global', polish: 'Wyszukiwanie globalne', braz_por: 'Busca global' },
    'ui.search.active_filter': { english: 'Active search filter:', german: 'Aktiver Suchfilter:', french: 'Filtre de recherche actif :', spanish: 'Filtro de búsqueda activo:', russian: 'Активный фильтр поиска:', polish: 'Aktywny filtr wyszukiwania:', braz_por: 'Filtro de busca ativo:' },
    'ui.search.clear_filter':  { english: 'Clear search', german: 'Suche beenden', french: 'Effacer la recherche', spanish: 'Borrar búsqueda', russian: 'Очистить поиск', polish: 'Wyczyść wyszukiwanie', braz_por: 'Limpar busca' },
    'ui.search.clear_filter_tooltip': { english: 'Reset filter and show all items again', german: 'Filter zurücksetzen und alle Einträge wieder anzeigen', french: 'Réinitialiser le filtre et afficher tous les éléments', spanish: 'Restablecer filtro y mostrar todos los elementos', russian: 'Сбросить фильтр и показать все элементы', polish: 'Zresetuj filtr i pokaż wszystkie elementy', braz_por: 'Redefinir filtro e mostrar todos os itens' },
    'ui.search.no_local_global_hits': { english: 'No matches in this tab — results from other modules:', german: 'Keine Treffer in diesem Tab — Ergebnisse aus anderen Modulen:', french: 'Aucun résultat dans cet onglet — résultats d\'autres modules :', spanish: 'Sin resultados en esta pestaña — resultados de otros módulos:', russian: 'Нет результатов в этой вкладке — результаты из других модулей:', polish: 'Brak wyników w tej zakładce — wyniki z innych modułów:', braz_por: 'Sem resultados nesta aba — resultados de outros módulos:' },

    // ==========================================
    // Misc
    // ==========================================
    'ui.action.view_3d': { english: 'View 3D Model', german: '3D-Modell anzeigen', french: 'Voir le modèle 3D', russian: 'Посмотреть 3D-модель' , spanish: 'Ver modelo 3D', polish: 'Zobacz model 3D', braz_por: 'Ver modelo 3D' },

    'ui.misc.yes': { english: 'Yes', german: 'Ja', french: 'Oui', russian: 'Да' , spanish: 'S\u00ed', polish: 'Tak', braz_por: 'Sim' },
    'ui.misc.no': { english: 'No',  german: 'Nein', french: 'Non', russian: 'Нет' , spanish: 'No', polish: 'Nie', braz_por: 'N\u00e3o' },
    'ui.misc.stage': { english: 'Stage', german: 'Stufe', french: 'Étape', russian: 'Этап' , spanish: 'Fase', polish: 'Etap', braz_por: 'Fase' },
    'ui.misc.difficulty': { english: 'difficulty', german: 'Schwierigkeit', french: 'difficulté', russian: 'сложность' , spanish: 'dificultad', polish: 'trudno\u015b\u0107', braz_por: 'dificuldade' },
    'ui.misc.event': { english: 'Event', german: 'Ereignis', french: 'Événement', russian: 'Событие' , spanish: 'Evento', polish: 'Wydarzenie', braz_por: 'Evento' },
    'ui.misc.icon': { english: 'Icon', german: 'Symbol', french: 'Icône', russian: 'Иконка' , spanish: 'Icono', polish: 'Ikona', braz_por: '\u00cdcone' },
    'ui.misc.unnamed': { english: '(unnamed)', german: '(unbenannt)', french: '(sans nom)', russian: '(без названия)' , spanish: '(sin nombre)', polish: '(bez nazwy)', braz_por: '(sem nome)' },
    'ui.misc.text': { english: 'Text', german: 'Text', french: 'Texte', russian: 'Текст' , spanish: 'Texto', polish: 'Tekst', braz_por: 'Texto' },

    // ==========================================
    // Tech-Tree specific labels
    // ==========================================
    'ui.tech.area': { english: 'Area',     german: 'Bereich',         french: 'Domaine',     russian: 'Область' , spanish: '\u00c1rea', polish: 'Dziedzina', braz_por: '\u00c1rea' },
    'ui.tech.tier': { english: 'Tier',     german: 'Stufe',           french: 'Niveau',      russian: 'Уровень' , spanish: 'Nivel', polish: 'Poziom', braz_por: 'N\u00edvel' },
    'ui.tech.category': { english: 'Category', german: 'Kategorie',       french: 'Catégorie',   russian: 'Категория' , spanish: 'Categor\u00eda', polish: 'Kategoria', braz_por: 'Categoria' },
    'ui.tech.rare': { english: 'Rare',     german: 'Selten',          french: 'Rare',        russian: 'Редкий' , spanish: 'Raro', polish: 'Rzadkie', braz_por: 'Raro' },
    'ui.tech.dangerous': { english: 'Dangerous',german: 'Gefährlich',      french: 'Dangereux',   russian: 'Опасный' , spanish: 'Peligroso', polish: 'Niebezpieczne', braz_por: 'Perigoso' },
    'ui.tech.reverse_engineerable': { english: 'Reverse-Engineerable', german: 'Reverse-Engineering möglich', french: 'Rétroconception possible', russian: 'Поддаётся обратной разработке' , spanish: 'Ingenier\u00eda inversa posible', polish: 'Mo\u017cliwa in\u017cynieria wsteczna', braz_por: 'Engenharia reversa poss\u00edvel' },
    'ui.tech.view_in_tree': { english: 'View in Tree', german: 'Im Baum anzeigen', french: 'Voir dans l’arbre', russian: 'Показать в дереве' , spanish: 'Ver en el \u00e1rbol', polish: 'Zobacz w drzewie', braz_por: 'Ver na \u00e1rvore' },

    // Resources tab
    'ui.resource.producers': { english: 'Producers',  german: 'Produzenten', french: 'Producteurs', russian: 'Производители' , spanish: 'Productores', polish: 'Producenci', braz_por: 'Produtores' },
    'ui.resource.consumers': { english: 'Consumers',  german: 'Verbraucher', french: 'Consommateurs', russian: 'Потребители' , spanish: 'Consumidores', polish: 'Konsumenci', braz_por: 'Consumidores' },
    'ui.resource.modifiers': { english: 'Modifiers Affecting This Resource', german: 'Modifikatoren für diese Ressource', french: 'Modificateurs affectant cette ressource', russian: 'Модификаторы для этого ресурса' , spanish: 'Modificadores que afectan a este recurso', polish: 'Modyfikatory wp\u0142ywaj\u0105ce na ten zas\u00f3b', braz_por: 'Modificadores que afetam este recurso' },
    'ui.resource.tradable': { english: 'Tradable',     german: 'Handelbar',  french: 'Commercialisable', russian: 'Продаваемый' , spanish: 'Comerciable', polish: 'Zbywalny', braz_por: 'Comercializ\u00e1vel' },
    'ui.resource.market_price': { english: 'Market Price', german: 'Marktpreis', french: 'Prix du marché', russian: 'Рыночная цена' , spanish: 'Precio de mercado', polish: 'Cena rynkowa', braz_por: 'Pre\u00e7o de mercado' },
    'ui.resource.market_supply': { english: 'Market Supply',german: 'Marktangebot', french: 'Offre du marché', russian: 'Рыночное предложение' , spanish: 'Oferta de mercado', polish: 'Poda\u017c rynkowa', braz_por: 'Oferta de mercado' },
    'ui.resource.max_stockpile': { english: 'Max Stockpile',german: 'Max. Lager',  french: 'Stock max',  russian: 'Макс. запас' , spanish: 'Reserva m\u00e1x.', polish: 'Maks. zapas', braz_por: 'Estoque m\u00e1x.' },
    'ui.resource.ai_weight': { english: 'AI Weight',    german: 'KI-Gewicht',  french: 'Poids IA',   russian: 'Вес ИИ' , spanish: 'Peso de IA', polish: 'Waga SI', braz_por: 'Peso da IA' },
    'ui.resource.axis_output': { english: 'Output',  german: 'Ausgabe',  french: 'Production', russian: 'Выработка' , spanish: 'Producci\u00f3n', polish: 'Produkcja', braz_por: 'Produ\u00e7\u00e3o' },
    'ui.resource.axis_upkeep': { english: 'Upkeep',  german: 'Unterhalt',french: 'Entretien',  russian: 'Содержание' , spanish: 'Mantenimiento', polish: 'Utrzymanie', braz_por: 'Manuten\u00e7\u00e3o' },
    'ui.resource.axis_cost': { english: 'Cost',    german: 'Kosten',   french: 'Coût',       russian: 'Стоимость' , spanish: 'Coste', polish: 'Koszt', braz_por: 'Custo' },

    // Trait detail
    'ui.trait.class': { english: 'Class',   german: 'Klasse',     french: 'Classe',  russian: 'Класс' , spanish: 'Clase', polish: 'Klasa', braz_por: 'Classe' },
    'ui.trait.rarity': { english: 'Rarity',  german: 'Seltenheit', french: 'Rareté',  russian: 'Редкость' , spanish: 'Rareza', polish: 'Rzadko\u015b\u0107', braz_por: 'Raridade' },
    'ui.trait.tier': { english: 'Tier',    german: 'Stufe',      french: 'Niveau',  russian: 'Уровень' , spanish: 'Nivel', polish: 'Poziom', braz_por: 'N\u00edvel' },
    'ui.trait.cost': { english: 'Cost',    german: 'Kosten',     french: 'Coût',    russian: 'Стоимость' , spanish: 'Coste', polish: 'Koszt', braz_por: 'Custo' },
};
