/**
 * UI string translations for the STNH Wiki interface.
 * Mod content (item names, descriptions) is handled separately by I18n.t().
 * This file handles navigation, tabs, filters, labels, messages etc.
 */
const UI_STRINGS = {
    // ==========================================
    // Navigation
    // ==========================================
    'ui.nav.hub':             { english: 'Hub', german: 'Hub', french: 'Accueil', russian: 'Главная' },
    'ui.nav.events':          { english: 'Events', german: 'Ereignisse', french: 'Événements', russian: 'События' },
    'ui.nav.tech':            { english: 'Tech Tree', german: 'Technologiebaum', french: 'Arbre technologique', russian: 'Дерево технологий' },
    'ui.nav.ships':           { english: 'Ships', german: 'Schiffe', french: 'Vaisseaux', russian: 'Корабли' },
    'ui.nav.buildings':       { english: 'Buildings', german: 'Geb\u00e4ude', french: 'B\u00e2timents', russian: 'Здания' },
    'ui.nav.traits':          { english: 'Traits', german: 'Eigenschaften', french: 'Traits', russian: 'Черты' },
    'ui.nav.governments':     { english: 'Governments', german: 'Regierungen', french: 'Gouvernements', russian: 'Правительства' },
    'ui.nav.megastructures':  { english: 'Megastructures', german: 'Megastrukturen', french: 'M\u00e9gastructures', russian: 'Мегаструктуры' },
    'ui.nav.anomalies':       { english: 'Anomalies', german: 'Anomalien', french: 'Anomalies', russian: 'Аномалии' },
    'ui.nav.empires':         { english: 'Empires', german: 'Reiche', french: 'Empires', russian: 'Империи' },
    'ui.nav.economy':         { english: 'Economy', german: 'Wirtschaft', french: '\u00c9conomie', russian: 'Экономика' },

    // ==========================================
    // Tab Buttons
    // ==========================================
    'ui.tab.ships':           { english: 'Ships', german: 'Schiffe', french: 'Vaisseaux', russian: 'Корабли' },
    'ui.tab.models':          { english: 'Models', german: 'Modelle', french: 'Modèles', russian: 'Модели' },
    'ui.tab.components':      { english: 'Components', german: 'Komponenten', french: 'Composants', russian: 'Компоненты' },
    'ui.tab.buildings':       { english: 'Buildings', german: 'Geb\u00e4ude', french: 'Bâtiments', russian: 'Здания' },
    'ui.tab.districts':       { english: 'Districts', german: 'Bezirke', french: 'Districts', russian: 'Районы' },
    'ui.tab.traits':          { english: 'Traits', german: 'Eigenschaften', french: 'Traits', russian: 'Черты' },
    'ui.tab.traditions':      { english: 'Traditions', german: 'Traditionen', french: 'Traditions', russian: 'Традиции' },
    'ui.tab.perks':           { english: 'Ascension Perks', german: 'Aufstiegsvorteile', french: 'Atouts d’ascension', russian: 'Навыки возвышения' },
    'ui.tab.governments':     { english: 'Governments', german: 'Regierungen', french: 'Gouvernements', russian: 'Правительства' },
    'ui.tab.civics':          { english: 'Civics', german: 'B\u00fcrgerrechte', french: 'Civiques', russian: 'Общественное устройство' },
    'ui.tab.authorities':     { english: 'Authorities', german: 'Autoritäten', french: 'Autorités', russian: 'Системы власти' },
    'ui.tab.policies':        { english: 'Policies', german: 'Richtlinien', french: 'Politiques', russian: 'Политики' },
    'ui.tab.edicts':          { english: 'Edicts', german: 'Edikte', french: 'Édits', russian: 'Указы' },
    'ui.tab.councilors':      { english: 'Councilors', german: 'Ratspositionen', french: 'Conseillers', russian: 'Советники' },
    'ui.tab.megastructures':  { english: 'Megastructures', german: 'Megastrukturen', french: 'Mégastructures', russian: 'Мегаструктуры' },
    'ui.tab.relics':          { english: 'Relics', german: 'Relikte', french: 'Reliques', russian: 'Реликвии' },
    'ui.tab.anomalies':       { english: 'Anomalies', german: 'Anomalien', french: 'Anomalies', russian: 'Аномалии' },
    'ui.tab.archaeology':     { english: 'Archaeology', german: 'Archäologie', french: 'Archéologie', russian: 'Археология' },
    'ui.tab.empires':         { english: 'Empires', german: 'Reiche', french: 'Empires', russian: 'Империи' },
    'ui.tab.species':         { english: 'Species', german: 'Spezies', french: 'Espèces', russian: 'Виды' },
    'ui.tab.jobs':            { english: 'Jobs', german: 'Berufe', french: 'Emplois', russian: 'Профессии' },
    'ui.tab.deposits':        { english: 'Deposits', german: 'Lagerstätten', french: 'Dépôts', russian: 'Месторождения' },
    'ui.view.list':           { english: '☰ List', german: '☰ Liste', french: '☰ Liste', russian: '☰ Список' },
    'ui.view.map':            { english: '✦ Galaxy Map', german: '✦ Galaxie-Karte', french: '✦ Carte galactique', russian: '✦ Карта галактики' },
    'ui.view.list_view':      { english: 'List View', german: 'Listenansicht', french: 'Vue liste', russian: 'Список' },
    'ui.view.tree_view':      { english: 'Tree View', german: 'Baumansicht', french: 'Vue arbre', russian: 'Дерево' },

    // ==========================================
    // Filter Labels & Default Options
    // ==========================================
    'ui.filter.class':           { english: 'Class', german: 'Klasse', french: 'Classe', russian: 'Класс' },
    'ui.filter.all_classes':     { english: 'All Classes', german: 'Alle Klassen', french: 'Toutes les classes', russian: 'Все классы' },
    'ui.filter.size':            { english: 'Size', german: 'Gr\u00f6\u00dfe', french: 'Taille', russian: 'Размер' },
    'ui.filter.all_sizes':       { english: 'All Sizes', german: 'Alle Gr\u00f6\u00dfen', french: 'Toutes les tailles', russian: 'Все размеры' },
    'ui.filter.type':            { english: 'Type', german: 'Typ', french: 'Type', russian: 'Тип' },
    'ui.filter.all_types':       { english: 'All Types', german: 'Alle Typen', french: 'Tous les types', russian: 'Все типы' },
    'ui.filter.category':        { english: 'Category', german: 'Kategorie', french: 'Cat\u00e9gorie', russian: 'Категория' },
    'ui.filter.all_categories':  { english: 'All Categories', german: 'Alle Kategorien', french: 'Toutes les cat\u00e9gories', russian: 'Все категории' },
    'ui.filter.tree':            { english: 'Tree', german: 'Baum', french: 'Arbre', russian: 'Дерево' },
    'ui.filter.all_trees':       { english: 'All Trees', german: 'Alle B\u00e4ume', french: 'Tous les arbres', russian: 'Все деревья' },
    'ui.filter.level':           { english: 'Level', german: 'Stufe', french: 'Niveau', russian: 'Уровень' },
    'ui.filter.all_levels':      { english: 'All Levels', german: 'Alle Stufen', french: 'Tous les niveaux', russian: 'Все уровни' },
    'ui.filter.authority':       { english: 'Authority', german: 'Autorit\u00e4t', french: 'Autorit\u00e9', russian: 'Система власти' },
    'ui.filter.all_authorities': { english: 'All Authorities', german: 'Alle Autorit\u00e4ten', french: 'Toutes les autorit\u00e9s', russian: 'Все системы власти' },
    'ui.filter.archetype':       { english: 'Archetype', german: 'Archetyp', french: 'Arch\u00e9type', russian: 'Архетип' },
    'ui.filter.all_archetypes':  { english: 'All Archetypes', german: 'Alle Archetypen', french: 'Tous les arch\u00e9types', russian: 'Все архетипы' },
    'ui.filter.faction':         { english: 'Faction', german: 'Fraktion', french: 'Faction', russian: 'Фракция' },
    'ui.filter.all_factions':    { english: 'All Factions', german: 'Alle Fraktionen', french: 'Toutes les factions', russian: 'Все фракции' },
    'ui.filter.namespace':       { english: 'Namespace', german: 'Namensraum', french: 'Espace de noms', russian: 'Пространство имён' },
    'ui.filter.all_namespaces':  { english: 'All Namespaces', german: 'Alle Namensr\u00e4ume', french: 'Tous les espaces de noms', russian: 'Все пространства имён' },
    'ui.filter.show_hidden':     { english: 'Show Hidden', german: 'Versteckte anzeigen', french: 'Afficher les cach\u00e9s', russian: 'Показать скрытые' },
    'ui.filter.triggered_only':  { english: 'Triggered Only', german: 'Nur ausgel\u00f6ste', french: 'D\u00e9clench\u00e9s uniquement', russian: 'Только триггерные' },
    'ui.filter.origins_only':    { english: 'Origins only', german: 'Nur Urspr\u00fcnge', french: 'Origines uniquement', russian: 'Только происхождения' },
    'ui.filter.area':            { english: 'Area', german: 'Bereich', french: 'Domaine', russian: 'Область' },
    'ui.filter.all_areas':       { english: 'All Areas', german: 'Alle Bereiche', french: 'Tous les domaines', russian: 'Все области' },
    'ui.filter.physics':         { english: 'Physics', german: 'Physik', french: 'Physique', russian: 'Физика' },
    'ui.filter.engineering':     { english: 'Engineering', german: 'Ingenieurwesen', french: 'Ingénierie', russian: 'Инженерия' },
    'ui.filter.society':         { english: 'Society', german: 'Gesellschaft', french: 'Société', russian: 'Общество' },
    'ui.filter.tier':            { english: 'Tier', german: 'Stufe', french: 'Niveau', russian: 'Уровень' },
    'ui.filter.tier_x':          { english: 'Tier %n', german: 'Stufe %n', french: 'Niveau %n', russian: 'Уровень %n' },
    'ui.filter.min_tier':        { english: 'Min Tier', german: 'Mindeststufe', french: 'Niveau min', russian: 'Мин. уровень' },
    'ui.filter.max_tier':        { english: 'Max Tier', german: 'Maximalstuf', french: 'Niveau max', russian: 'Макс. уровень' },
    'ui.filter.show_no_model':   { english: 'Show ships without 3D model', german: 'Schiffe ohne 3D-Modell anzeigen', french: 'Afficher les vaisseaux sans mod\u00e8le 3D', russian: 'Показать корабли без 3D-модели' },

    // Event types
    'ui.event_type.country_event':   { english: 'Country', german: 'Land', french: 'Pays', russian: 'Страна' },
    'ui.event_type.ship_event':      { english: 'Ship', german: 'Schiff', french: 'Vaisseau', russian: 'Корабль' },
    'ui.event_type.planet_event':    { english: 'Planet', german: 'Planet', french: 'Plan\u00e8te', russian: 'Планета' },
    'ui.event_type.fleet_event':     { english: 'Fleet', german: 'Flotte', french: 'Flotte', russian: 'Флот' },
    'ui.event_type.situation_event': { english: 'Situation', german: 'Situation', french: 'Situation', russian: 'Ситуация' },
    'ui.event_type.observer_event':  { english: 'Observer', german: 'Beobachter', french: 'Observateur', russian: 'Наблюдатель' },
    'ui.event_type.pop_event':       { english: 'Pop', german: 'Bevölkerung', french: 'Population', russian: 'Пласт' },

    // Ship class labels
    'ui.ship_class.military':            { english: 'Military', german: 'Milit\u00e4r', french: 'Militaire', russian: 'Военный' },
    'ui.ship_class.starbase':            { english: 'Starbase', german: 'Sternenbasis', french: 'Base stellaire', russian: 'Звёздная база' },
    'ui.ship_class.science':             { english: 'Science', german: 'Wissenschaft', french: 'Science', russian: 'Научный' },
    'ui.ship_class.colonizer':           { english: 'Colonizer', german: 'Kolonisator', french: 'Colonisateur', russian: 'Колонизатор' },
    'ui.ship_class.constructor':         { english: 'Constructor', german: 'Konstruktor', french: 'Constructeur', russian: 'Конструктор' },
    'ui.ship_class.transport':           { english: 'Transport', german: 'Transport', french: 'Transport', russian: 'Транспорт' },
    'ui.ship_class.mining_station':      { english: 'Mining Station', german: 'Minenstation', french: 'Station mini\u00e8re', russian: 'Горнодобывающая станция' },
    'ui.ship_class.research_station':    { english: 'Research Station', german: 'Forschungsstation', french: 'Station de recherche', russian: 'Исследовательская станция' },
    'ui.ship_class.observation_station': { english: 'Observation Station', german: 'Beobachtungsstation', french: 'Station d\'observation', russian: 'Наблюдательная станция' },
    'ui.ship_class.military_station':    { english: 'Military Station', german: 'Milit\u00e4rstation', french: 'Station militaire', russian: 'Военная станция' },

    // Component type labels
    'ui.comp_type.weapon':      { english: 'Weapon', german: 'Waffe', french: 'Arme', russian: 'Оружие' },
    'ui.comp_type.utility':     { english: 'Utility', german: 'Hilfssystem', french: 'Utilitaire', russian: 'Утилита' },
    'ui.comp_type.strike_craft':{ english: 'Strike Craft', german: 'Jagdfl\u00fcgler', french: 'Chasseur', russian: 'Штурмовик' },

    // Component size labels
    'ui.comp_size.small':          { english: 'Small', german: 'Klein', french: 'Petit', russian: 'Малый' },
    'ui.comp_size.medium':         { english: 'Medium', german: 'Mittel', french: 'Moyen', russian: 'Средний' },
    'ui.comp_size.large':          { english: 'Large', german: 'Gro\u00df', french: 'Grand', russian: 'Большой' },
    'ui.comp_size.extra_large':    { english: 'Extra Large', german: 'Sehr gro\u00df', french: 'Tr\u00e8s grand', russian: 'Очень большой' },
    'ui.comp_size.titanic':        { english: 'Titanic', german: 'Titanisch', french: 'Titanesque', russian: 'Титанический' },
    'ui.comp_size.torpedo':        { english: 'Torpedo', german: 'Torpedo', french: 'Torpedo', russian: 'Торпеда' },
    'ui.comp_size.point_defence':  { english: 'Point Defence', german: 'Punktverteidigung', french: 'D\u00e9fense ponctuelle', russian: 'Точечная оборона' },
    'ui.comp_size.aux':            { english: 'Aux', german: 'Zusatz', french: 'Auxiliaire', russian: 'Вспомогательный' },
    'ui.comp_size.planet_killer':  { english: 'Planet Killer', german: 'Planetenvernichter', french: 'D\u00e9vastateur de plan\u00e8te', russian: 'Уничтожитель планет' },

    // Building category labels
    'ui.bld_cat.amenity':       { english: 'Amenity', german: 'Einrichtung', french: 'Commodit\u00e9', russian: 'Удобство' },
    'ui.bld_cat.army':          { english: 'Army', german: 'Armee', french: 'Arm\u00e9e', russian: 'Армия' },
    'ui.bld_cat.government':    { english: 'Government', german: 'Regierung', french: 'Gouvernement', russian: 'Правительство' },
    'ui.bld_cat.manufacturing': { english: 'Manufacturing', german: 'Fertigung', french: 'Fabrication', russian: 'Производство' },
    'ui.bld_cat.pop_assembly':  { english: 'Pop Assembly', german: 'Bevölkerungsmontageanl.', french: 'Assemblage de pop.', russian: 'Сборка пласта' },
    'ui.bld_cat.research':      { english: 'Research', german: 'Forschung', french: 'Recherche', russian: 'Исследование' },
    'ui.bld_cat.resource':      { english: 'Resource', german: 'Ressource', french: 'Ressource', russian: 'Ресурс' },
    'ui.bld_cat.trade':         { english: 'Trade', german: 'Handel', french: 'Commerce', russian: 'Торговля' },
    'ui.bld_cat.unity':         { english: 'Unity', german: 'Einheit', french: 'Unit\u00e9', russian: 'Единство' },

    // Quadrant labels (empires page)
    'ui.quadrant.all':   { english: 'All', german: 'Alle', french: 'Tous', russian: 'Все' },
    'ui.quadrant.alpha': { english: '\u03b1 Alpha', german: '\u03b1 Alpha', french: '\u03b1 Alpha', russian: '\u03b1 Альфа' },
    'ui.quadrant.beta':  { english: '\u03b2 Beta', german: '\u03b2 Beta', french: '\u03b2 Beta', russian: '\u03b2 Бета' },
    'ui.quadrant.gamma': { english: '\u03b3 Gamma', german: '\u03b3 Gamma', french: '\u03b3 Gamma', russian: '\u03b3 Гамма' },
    'ui.quadrant.delta': { english: '\u03b4 Delta', german: '\u03b4 Delta', french: '\u03b4 Delta', russian: '\u03b4 Дельта' },
    'ui.quadrant.major': { english: '\u2605 Major', german: '\u2605 Major', french: '\u2605 Majeur', russian: '\u2605 Основные' },
    'ui.quadrant.alt':   { english: '\u25c8 Alt', german: '\u25c8 Alt', french: '\u25c8 Alt', russian: '\u25c8 Альт' },

    // Filter by empire placeholder
    'ui.filter.empire_placeholder': { english: 'Filter by empire...', german: 'Nach Reich filtern...', french: 'Filtrer par empire...', russian: 'Фильтр по империи...' },

    // ==========================================
    // Search Placeholders
    // ==========================================
    'ui.search.hub':          { english: 'Search all items...', german: 'Alle Eintr\u00e4ge durchsuchen...', french: 'Rechercher tous les \u00e9l\u00e9ments...', russian: 'Поиск всех элементов...' },
    'ui.search.ships':        { english: 'Search ships & components...', german: 'Schiffe & Komponenten durchsuchen...', french: 'Rechercher vaisseaux & composants...', russian: 'Поиск кораблей и компонентов...' },
    'ui.search.buildings':    { english: 'Search buildings & districts...', german: 'Geb\u00e4ude & Bezirke durchsuchen...', french: 'Rechercher b\u00e2timents & districts...', russian: 'Поиск зданий и районов...' },
    'ui.search.traits':       { english: 'Search traits, traditions & perks...', german: 'Eigenschaften, Traditionen & Vorteile durchsuchen...', french: 'Rechercher traits, traditions & atouts...', russian: 'Поиск черт, традиций и навыков...' },
    'ui.search.governments':  { english: 'Search governments, civics, policies...', german: 'Regierungen, B\u00fcrgerrechte, Richtlinien durchsuchen...', french: 'Rechercher gouvernements, civiques, politiques...', russian: 'Поиск правительств, общества, политик...' },
    'ui.search.megastructures': { english: 'Search megastructures & relics...', german: 'Megastrukturen & Relikte durchsuchen...', french: 'Rechercher m\u00e9gastructures & reliques...', russian: 'Поиск мегаструктур и реликвий...' },
    'ui.search.anomalies':    { english: 'Search anomalies & archaeology...', german: 'Anomalien & Arch\u00e4ologie durchsuchen...', french: 'Rechercher anomalies & arch\u00e9ologie...', russian: 'Поиск аномалий и археологии...' },
    'ui.search.empires':      { english: 'Search empires & species...', german: 'Reiche & Spezies durchsuchen...', french: 'Rechercher empires & esp\u00e8ces...', russian: 'Поиск империй и видов...' },
    'ui.search.economy':      { english: 'Search jobs & deposits...', german: 'Berufe & Lagerst\u00e4tten durchsuchen...', french: 'Rechercher emplois & d\u00e9p\u00f4ts...', russian: 'Поиск профессий и месторождений...' },
    'ui.search.events':       { english: 'Search events... (id:, ns:, faction:)', german: 'Ereignisse durchsuchen... (id:, ns:, faction:)', french: 'Rechercher \u00e9v\u00e9nements... (id:, ns:, faction:)', russian: 'Поиск событий... (id:, ns:, faction:)' },

    // ==========================================
    // Detail Section Titles
    // ==========================================
    'ui.detail.detail':           { english: 'Detail', german: 'Detail', french: 'Détail', russian: 'Подробности' },
    'ui.detail.stats':            { english: 'Stats', german: 'Werte', french: 'Statistiques', russian: 'Характеристики' },
    'ui.detail.prerequisites':    { english: 'Prerequisites', german: 'Voraussetzungen', french: 'Prérequis', russian: 'Предусловия' },
    'ui.detail.resources':        { english: 'Resources', german: 'Ressourcen', french: 'Ressources', russian: 'Ресурсы' },
    'ui.detail.modifiers':        { english: 'Modifiers', german: 'Modifikatoren', french: 'Modificateurs', russian: 'Модификаторы' },
    'ui.detail.section_slots':    { english: 'Section Slots', german: 'Sektionspl\u00e4tze', french: 'Emplacements de section', russian: 'Слоты секций' },
    'ui.detail.tags':             { english: 'Tags', german: 'Tags', french: 'Étiquettes', russian: 'Метки' },
    'ui.detail.description':      { english: 'Description', german: 'Beschreibung', french: 'Description', russian: 'Описание' },
    'ui.detail.opposites':        { english: 'Opposites', german: 'Gegenteile', french: 'Opposés', russian: 'Противоположности' },
    'ui.detail.requirements':     { english: 'Requirements', german: 'Anforderungen', french: 'Exigences', russian: 'Требования' },
    'ui.detail.on_enabled':       { english: 'On Enabled', german: 'Bei Aktivierung', french: 'À l’activation', russian: 'При активации' },
    'ui.detail.tradition_swaps':  { english: 'Tradition Swaps', german: 'Traditionstausch', french: 'Échanges de traditions', russian: 'Замены традиций' },
    'ui.detail.upgrades_to':      { english: 'Upgrades To', german: 'Ausbau zu', french: 'Amélioration vers', russian: 'Улучшается до' },
    'ui.detail.potential':        { english: 'Potential', german: 'Potenzial', french: 'Potentiel', russian: 'Потенциал' },
    'ui.detail.leader_possible':  { english: 'Leader Requirements', german: 'Anf\u00fchreranforderungen', french: 'Exigences de chef', russian: 'Требования к лидеру' },
    'ui.detail.options':          { english: 'Options', german: 'Optionen', french: 'Options', russian: 'Варианты' },
    'ui.detail.weight':           { english: 'Weight', german: 'Gewichtung', french: 'Poids', russian: 'Вес' },
    'ui.detail.active_effect':    { english: 'Active Effect', german: 'Aktiver Effekt', french: 'Effet actif', russian: 'Активный эффект' },
    'ui.detail.possible':         { english: 'Possible', german: 'M\u00f6glich', french: 'Possible', russian: 'Возможно' },
    'ui.detail.on_build_complete':{ english: 'On Build Complete', german: 'Bei Fertigstellung', french: 'À la fin de construction', russian: 'По завершении строительства' },
    'ui.detail.success_outcomes': { english: 'Success Outcomes', german: 'Erfolgsergebnisse', french: 'Résultats réussis', russian: 'Успешные исходы' },
    'ui.detail.spawn_chance':     { english: 'Spawn Chance', german: 'Erscheinungschance', french: 'Chance d’apparition', russian: 'Шанс появления' },
    'ui.detail.stages':           { english: 'Stages', german: 'Stufen', french: 'Étapes', russian: 'Этапы' },
    'ui.detail.info':             { english: 'Info', german: 'Info', french: 'Infos', russian: 'Инфо' },
    'ui.detail.ethics':           { english: 'Ethics', german: 'Ethiken', french: 'Éthiques', russian: 'Этика' },
    'ui.detail.civics':           { english: 'Civics', german: 'B\u00fcrgerrechte', french: 'Civiques', russian: 'Общественное устройство' },
    'ui.detail.species':          { english: 'Species', german: 'Spezies', french: 'Espèces', russian: 'Виды' },
    'ui.detail.ruler':            { english: 'Ruler', german: 'Herrscher', french: 'Dirigeant', russian: 'Правитель' },
    'ui.detail.portraits':        { english: 'Portraits', german: 'Portr\u00e4ts', french: 'Portraits', russian: 'Портреты' },
    'ui.detail.drop_weight':      { english: 'Drop Weight', german: 'Fallgewichtung', french: 'Poids de drop', russian: 'Вес выпадения' },
    'ui.detail.3d_model':         { english: '3D Model', german: '3D-Modell', french: 'Modèle 3D', russian: '3D-модель' },
    'ui.detail.required_traditions': { english: 'Required Traditions', german: 'Benötigte Traditionen', french: 'Traditions requises', russian: 'Нужные традиции' },
    'ui.detail.min_perks':        { english: 'Required Ascension Perks', german: 'Benötigte Ascension Perks', french: 'Atouts d’ascension requis', russian: 'Нужные навыки возвышения' },
    'ui.detail.required_flags':   { english: 'Required Empire', german: 'Benötigtes Reich', french: 'Empire requis', russian: 'Нужная империя' },

    // ==========================================
    // Meta Labels
    // ==========================================
    'ui.meta.id':              { english: 'ID', german: 'ID', french: 'ID', russian: 'ID' },
    'ui.meta.class':           { english: 'Class', german: 'Klasse', french: 'Classe', russian: 'Класс' },
    'ui.meta.type':            { english: 'Type', german: 'Typ', french: 'Type', russian: 'Тип' },
    'ui.meta.size':            { english: 'Size', german: 'Gr\u00f6\u00dfe', french: 'Taille', russian: 'Размер' },
    'ui.meta.file':            { english: 'File', german: 'Datei', french: 'Fichier', russian: 'Файл' },
    'ui.meta.hp':              { english: 'HP', german: 'TP', french: 'PV', russian: 'ЗД' },
    'ui.meta.speed':           { english: 'Speed', german: 'Geschwindigkeit', french: 'Vitesse', russian: 'Скорость' },
    'ui.meta.build_time':      { english: 'Build Time', german: 'Bauzeit', french: 'Temps de construction', russian: 'Время строительства' },
    'ui.meta.power':           { english: 'Power', german: 'Energie', french: 'Énergie', russian: 'Энергия' },
    'ui.meta.damage':          { english: 'Damage', german: 'Schaden', french: 'Dégâts', russian: 'Урон' },
    'ui.meta.range':           { english: 'Range', german: 'Reichweite', french: 'Portée', russian: 'Дальность' },
    'ui.meta.accuracy':        { english: 'Accuracy', german: 'Genauigkeit', french: 'Précision', russian: 'Точность' },
    'ui.meta.tracking':        { english: 'Tracking', german: 'Zielverfolgung', french: 'Suivi', russian: 'Слежение' },
    'ui.meta.category':        { english: 'Category', german: 'Kategorie', french: 'Catégorie', russian: 'Категория' },
    'ui.meta.rarity':          { english: 'Rarity', german: 'Seltenheit', french: 'Rareté', russian: 'Редкость' },
    'ui.meta.tier':            { english: 'Tier', german: 'Stufe', french: 'Niveau', russian: 'Уровень' },
    'ui.meta.tree':            { english: 'Tree', german: 'Baum', french: 'Arbre', russian: 'Дерево' },
    'ui.meta.role':            { english: 'Role', german: 'Rolle', french: 'Rôle', russian: 'Роль' },
    'ui.meta.cost':            { english: 'Cost', german: 'Kosten', french: 'Coût', russian: 'Стоимость' },
    'ui.meta.ruler':           { english: 'Ruler', german: 'Herrscher', french: 'Dirigeant', russian: 'Правитель' },
    'ui.meta.election':        { english: 'Election', german: 'Wahl', french: 'Élection', russian: 'Выборы' },
    'ui.meta.duration':        { english: 'Duration', german: 'Dauer', french: 'Durée', russian: 'Длительность' },
    'ui.meta.entity':          { english: 'Entity', german: 'Entit\u00e4t', french: 'Entité', russian: 'Сущность' },
    'ui.meta.upgrade_from':    { english: 'Upgrade From', german: 'Ausbau von', french: 'Amélioration depuis', russian: 'Улучшается из' },
    'ui.meta.sensor_range':    { english: 'Sensor Range', german: 'Sensorreichweite', french: 'Portée du capteur', russian: 'Дальность сенсора' },
    'ui.meta.activation_duration': { english: 'Activation Duration', german: 'Aktivierungsdauer', french: 'Durée d’activation', russian: 'Длительность активации' },
    'ui.meta.score':           { english: 'Score', german: 'Punkte', french: 'Score', russian: 'Очки' },
    'ui.meta.desc':            { english: 'Desc', german: 'Beschr.', french: 'Desc', russian: 'Опис.' },
    'ui.meta.level':           { english: 'Level', german: 'Stufe', french: 'Niveau', russian: 'Уровень' },
    'ui.meta.picture':         { english: 'Picture', german: 'Bild', french: 'Image', russian: 'Изображение' },
    'ui.meta.max_once':        { english: 'Max Once', german: 'Max. einmal', french: 'Maximum une fois', russian: 'Макс. один раз' },
    'ui.meta.max_instances':   { english: 'Max Instances', german: 'Max. Instanzen', french: 'Instances max.', russian: 'Макс. экземпляры' },
    'ui.meta.authority':       { english: 'Authority', german: 'Autorit\u00e4t', french: 'Autorité', russian: 'Система власти' },
    'ui.meta.government':      { english: 'Government', german: 'Regierung', french: 'Gouvernement', russian: 'Правительство' },
    'ui.meta.origin':          { english: 'Origin', german: 'Ursprung', french: 'Origine', russian: 'Происхождение' },
    'ui.meta.ship_prefix':     { english: 'Ship Prefix', german: 'Schiffspr\u00e4fix', french: 'Préfixe de vaisseau', russian: 'Префикс корабля' },
    'ui.meta.culture':         { english: 'Culture', german: 'Kultur', french: 'Culture', russian: 'Культура' },
    'ui.meta.homeworld':       { english: 'Homeworld', german: 'Heimatwelt', french: 'Monde natal', russian: 'Родной мир' },
    'ui.meta.planet_class':    { english: 'Planet Class', german: 'Planetenklasse', french: 'Classe planétaire', russian: 'Класс планеты' },
    'ui.meta.system':          { english: 'System', german: 'System', french: 'Système', russian: 'Система' },
    'ui.meta.archetype':       { english: 'Archetype', german: 'Archetyp', french: 'Archétype', russian: 'Архетип' },
    'ui.meta.uplifted_into':   { english: 'Uplifted Into', german: 'Erhoben zu', french: 'Élevé en', russian: 'Возвышен до' },
    'ui.meta.gender':          { english: 'Gender', german: 'Geschlecht', french: 'Genre', russian: 'Пол' },
    'ui.meta.building_icon':   { english: 'Building Icon', german: 'Geb\u00e4udesymbol', french: 'Icône de bâtiment', russian: 'Иконка здания' },
    'ui.meta.condition':       { english: 'Condition', german: 'Bedingung', french: 'Condition', russian: 'Условие' },
    'ui.meta.capped_by_modifier': { english: 'Capped by Modifier', german: 'Begrenzt durch Modifikator', french: 'Limité par modificateur', russian: 'Ограничено модификатором' },
    'ui.meta.null_deposit':    { english: 'Null Deposit', german: 'Leer-Lagerst\u00e4tte', french: 'Dépôt vide', russian: 'Пустое месторождение' },
    'ui.meta.for_colonizable': { english: 'For Colonizable', german: 'F\u00fcr Kolonisierbare', french: 'Pour colonisable', russian: 'Для колонизируемых' },
    'ui.meta.stages':          { english: 'Stages', german: 'Stufen', french: 'Étapes', russian: 'Этапы' },
    'ui.meta.civic':           { english: 'Civic', german: 'B\u00fcrgerrecht', french: 'Civique', russian: 'Общественное' },

    // ==========================================
    // Card Meta Prefixes
    // ==========================================
    'ui.card.tech':            { english: 'Tech', german: 'Tech', french: 'Tech', russian: 'Тех' },
    'ui.card.build':           { english: 'Build', german: 'Bau', french: 'Construction', russian: 'Строительство' },
    'ui.card.from':            { english: 'From', german: 'Von', french: 'De', russian: 'От' },
    'ui.card.score':           { english: 'Score', german: 'Punkte', french: 'Score', russian: 'Очки' },
    'ui.card.duration':        { english: 'Duration', german: 'Dauer', french: 'Durée', russian: 'Длительность' },
    'ui.card.options':         { english: 'options', german: 'Optionen', french: 'options', russian: 'варианты' },
    'ui.card.outcomes':        { english: 'outcomes', german: 'Ergebnisse', french: 'résultats', russian: 'исходы' },
    'ui.card.stages':          { english: 'stages', german: 'Stufen', french: 'étapes', russian: 'этапы' },
    'ui.card.ethics':          { english: 'ethics', german: 'Ethiken', french: 'éthiques', russian: 'этика' },

    // ==========================================
    // Badges
    // ==========================================
    'ui.badge.origin':         { english: 'Origin', german: 'Ursprung', french: 'Origine', russian: 'Происхождение' },
    'ui.badge.ambition':       { english: 'Ambition', german: 'Ambition', french: 'Ambition', russian: 'Амбиция' },
    'ui.badge.unique':         { english: 'Unique', german: 'Einzigartig', french: 'Unique', russian: 'Уникальное' },
    'ui.badge.capital':        { english: 'Capital', german: 'Hauptstadt', french: 'Capitale', russian: 'Столица' },
    'ui.badge.colonizable':    { english: 'Colonizable', german: 'Kolonisierbar', french: 'Colonisable', russian: 'Колонизируемая' },
    'ui.badge.has_heir':       { english: 'Has Heir', german: 'Hat Erben', french: 'A un héritier', russian: 'Есть наследник' },
    'ui.badge.triggered_only': { english: 'triggered only', german: 'nur ausgel\u00f6st', french: 'déclenché uniquement', russian: 'только триггерное' },
    'ui.badge.hidden':         { english: 'hidden', german: 'versteckt', french: 'caché', russian: 'скрытое' },
    'ui.badge.required':       { english: 'Required', german: 'Pflicht', french: 'Requis', russian: 'Обязательное' },
    'ui.badge.fire_once':      { english: 'fire once', german: 'einmalig', french: 'une seule fois', russian: 'один раз' },
    'ui.badge.diplomatic':     { english: 'diplomatic', german: 'diplomatisch', french: 'diplomatique', russian: 'дипломатическое' },

    // ==========================================
    // Hub Page
    // ==========================================
    'ui.hub.subtitle':         { english: 'Comprehensive off-game reference for the STNH Stellaris mod', german: 'Umfassendes Off-Game-Nachschlagewerk f\u00fcr die STNH Stellaris-Mod', french: 'Référence complète hors-jeu pour le mod STNH Stellaris', russian: 'Полный внеигровой справочник по моду STNH для Stellaris' },
    'ui.hub.total_items':      { english: 'Total Items', german: 'Gesamtanzahl', french: 'Total d’éléments', russian: 'Всего элементов' },
    'ui.hub.last_update':      { english: 'Last Update', german: 'Letztes Update', french: 'Dernière mise à jour', russian: 'Последнее обновление' },
    'ui.hub.desc_events':      { english: 'Browse all events with full localisation in 7 languages.', german: 'Alle Ereignisse mit voller Lokalisierung in 7 Sprachen durchsuchen.', french: 'Parcourir tous les événements avec une localisation complète en 7 langues.', russian: 'Просмотр всех событий с полной локализацией на 7 языках.' },
    'ui.hub.desc_tech':        { english: 'Interactive technology tree with prerequisites and unlocks.', german: 'Interaktiver Technologiebaum mit Voraussetzungen und Freischaltungen.', french: 'Arbre technologique interactif avec prérequis et déblocages.', russian: 'Интерактивное дерево технологий с предусловиями и открытиями.' },
    'ui.hub.desc_ships':       { english: 'Ship classes, sizes, components, and faction-specific designs.', german: 'Schiffsklassen, Gr\u00f6\u00dfen, Komponenten und fraktionsspezifische Designs.', french: 'Classes de vaisseaux, tailles, composants et designs spécifiques aux factions.', russian: 'Классы, размеры, компоненты кораблей и дизайны фракций.' },
    'ui.hub.desc_buildings':   { english: 'Planetary buildings, districts, and their production chains.', german: 'Planetare Geb\u00e4ude, Bezirke und ihre Produktionsketten.', french: 'Bâtiments planétaires, districts et leurs chaînes de production.', russian: 'Планетарные здания, районы и цепочки производства.' },
    'ui.hub.desc_traits':      { english: 'Leader traits, traditions, ascension perks and their effects.', german: 'Anf\u00fchrereigenschaften, Traditionen, Aufstiegsvorteile und ihre Effekte.', french: 'Traits des chefs, traditions, atouts d’ascension et leurs effets.', russian: 'Черты лидеров, традиции, навыки возвышения и их эффекты.' },
    'ui.hub.desc_governments': { english: 'Government types, civics, authorities, policies, and edicts.', german: 'Regierungsformen, B\u00fcrgerrechte, Autorit\u00e4ten, Richtlinien und Edikte.', french: 'Types de gouvernements, civiques, autorités, politiques et édits.', russian: 'Типы правительств, общественное устройство, системы власти, политики и указы.' },
    'ui.hub.desc_megastructures': { english: 'Megastructure types, relics, build stages, and requirements.', german: 'Megastrukturtypen, Relikte, Baustufen und Anforderungen.', french: 'Types de mégastructures, reliques, étapes de construction et exigences.', russian: 'Типы мегаструктур, реликвии, стадии строительства и требования.' },
    'ui.hub.desc_anomalies':   { english: 'Anomaly categories, archaeological sites, outcomes, and events.', german: 'Anomaliekategorien, arch\u00e4ologische St\u00e4tten, Ergebnisse und Ereignisse.', french: 'Catégories d’anomalies, sites archéologiques, résultats et événements.', russian: 'Категории аномалий, археологические памятники, результаты и события.' },
    'ui.hub.desc_empires':     { english: 'Prescripted empires, species classes, factions, and portraits.', german: 'Vordefinierte Reiche, Speziesklassen, Fraktionen und Portr\u00e4ts.', french: 'Empires prédéfinis, classes d’espèces, factions et portraits.', russian: 'Преднастроенные империи, классы видов, фракции и портреты.' },
    'ui.hub.desc_economy':     { english: 'Pop jobs, deposits, resource production, and economic chains.', german: 'Pop-Berufe, Lagerst\u00e4tten, Ressourcenproduktion und Wirtschaftsketten.', french: 'Emplois de population, dépôts, production de ressources et chaînes économiques.', russian: 'Профессии популяции, месторождения, производство ресурсов и экономические цепочки.' },

    // ==========================================
    // Event Detail Specific
    // ==========================================
    'ui.event.description':        { english: 'Description', german: 'Beschreibung', french: 'Description', russian: 'Описание' },
    'ui.event.condition':          { english: 'Condition', german: 'Bedingung', french: 'Condition', russian: 'Условие' },
    'ui.event.trigger_conditions': { english: 'Trigger Conditions', german: 'Ausl\u00f6sebedingungen', french: 'Conditions de déclenchement', russian: 'Условия триггера' },
    'ui.event.immediate_effects':  { english: 'Immediate Effects', german: 'Sofortige Effekte', french: 'Effets immédiats', russian: 'Немедленные эффекты' },
    'ui.event.options':            { english: 'Options', german: 'Optionen', french: 'Options', russian: 'Варианты' },
    'ui.event.after_effects':      { english: 'After Effects', german: 'Nachfolgende Effekte', french: 'Effets ultérieurs', russian: 'Последующие эффекты' },
    'ui.event.mtth':               { english: 'Mean Time to Happen', german: 'Durchschnittliche Ausl\u00f6sezeit', french: 'Temps moyen d’occurrence', russian: 'Среднее время до срабатывания' },
    'ui.event.on_actions':         { english: 'Triggered by On-Actions', german: 'Ausgel\u00f6st durch On-Actions', french: 'Déclenché par des actions', russian: 'Триггерится действиями' },
    'ui.event.triggered_by':       { english: 'Triggered By', german: 'Ausgel\u00f6st von', french: 'Déclenché par', russian: 'Триггерится' },
    'ui.event.triggers':           { english: 'Triggers', german: 'L\u00f6st aus', french: 'Déclenche', russian: 'Запускает' },
    'ui.event.requires':           { english: 'Requires', german: 'Erfordert', french: 'Nécessite', russian: 'Требует' },
    'ui.event.shows_if':           { english: 'Shows if', german: 'Zeigt wenn', french: 'Affiché si', russian: 'Показывается если' },
    'ui.event.effects':            { english: 'Effects', german: 'Effekte', french: 'Effets', russian: 'Эффекты' },
    'ui.event.event_detail':       { english: 'Event Detail', german: 'Ereignisdetail', french: 'Détail de l’événement', russian: 'Подробности события' },
    'ui.event.event_chain':        { english: 'Event Chain', german: 'Ereigniskette', french: 'Chaîne d’événements', russian: 'Цепочка событий' },
    'ui.event.namespaces':         { english: 'Namespaces', german: 'Namensr\u00e4ume', french: 'Espaces de noms', russian: 'Пространства имён' },

    // ==========================================
    // Type Labels (Global Search)
    // ==========================================
    'ui.type.event':           { english: 'Event', german: 'Ereignis', french: 'Événement', russian: 'Событие' },
    'ui.type.ship':            { english: 'Ship', german: 'Schiff', french: 'Vaisseau', russian: 'Корабль' },
    'ui.type.component':       { english: 'Component', german: 'Komponente', french: 'Composant', russian: 'Компонент' },
    'ui.type.building':        { english: 'Building', german: 'Geb\u00e4ude', french: 'Bâtiment', russian: 'Здание' },
    'ui.type.district':        { english: 'District', german: 'Bezirk', french: 'District', russian: 'Район' },
    'ui.type.trait':           { english: 'Trait', german: 'Eigenschaft', french: 'Trait', russian: 'Черта' },
    'ui.type.tradition':       { english: 'Tradition', german: 'Tradition', french: 'Tradition', russian: 'Традиция' },
    'ui.type.ascension_perk':  { english: 'Ascension Perk', german: 'Aufstiegsvorteil', french: 'Atout d’ascension', russian: 'Навык возвышения' },
    'ui.type.government':      { english: 'Government', german: 'Regierung', french: 'Gouvernement', russian: 'Правительство' },
    'ui.type.civic':           { english: 'Civic', german: 'B\u00fcrgerrecht', french: 'Civique', russian: 'Общественное' },
    'ui.type.authority':       { english: 'Authority', german: 'Autorit\u00e4t', french: 'Autorité', russian: 'Система власти' },
    'ui.type.policy':          { english: 'Policy', german: 'Richtlinie', french: 'Politique', russian: 'Политика' },
    'ui.type.edict':           { english: 'Edict', german: 'Edikt', french: 'Édit', russian: 'Указ' },
    'ui.type.megastructure':   { english: 'Megastructure', german: 'Megastruktur', french: 'Mégastructure', russian: 'Мегаструктура' },
    'ui.type.relic':           { english: 'Relic', german: 'Relikt', french: 'Relique', russian: 'Реликвия' },
    'ui.type.anomaly':         { english: 'Anomaly', german: 'Anomalie', french: 'Anomalie', russian: 'Аномалия' },
    'ui.type.archaeology':     { english: 'Archaeology', german: 'Arch\u00e4ologie', french: 'Archéologie', russian: 'Археология' },
    'ui.type.empire':          { english: 'Empire', german: 'Reich', french: 'Empire', russian: 'Империя' },
    'ui.type.species':         { english: 'Species', german: 'Spezies', french: 'Espèces', russian: 'Вид' },
    'ui.type.job':             { english: 'Job', german: 'Beruf', french: 'Emploi', russian: 'Профессия' },
    'ui.type.deposit':         { english: 'Deposit', german: 'Lagerst\u00e4tte', french: 'Dépôt', russian: 'Месторождение' },
    'ui.type.technology':      { english: 'Technology', german: 'Technologie', french: 'Technologie', russian: 'Технология' },

    // ==========================================
    // Loading / Empty / Error States
    // ==========================================
    'ui.loading.ships':        { english: 'Loading ship data', german: 'Lade Schiffsdaten', french: 'Chargement des données de vaisseaux', russian: 'Загрузка данных кораблей' },
    'ui.loading.buildings':    { english: 'Loading building data', german: 'Lade Geb\u00e4udedaten', french: 'Chargement des données de bâtiments', russian: 'Загрузка данных зданий' },
    'ui.loading.traits':       { english: 'Loading trait data', german: 'Lade Eigenschaftsdaten', french: 'Chargement des données de traits', russian: 'Загрузка данных черт' },
    'ui.loading.governments':  { english: 'Loading government data', german: 'Lade Regierungsdaten', french: 'Chargement des données de gouvernements', russian: 'Загрузка данных правительств' },
    'ui.loading.megastructures': { english: 'Loading megastructure data', german: 'Lade Megastrukturdaten', french: 'Chargement des données de mégastructures', russian: 'Загрузка данных мегаструктур' },
    'ui.loading.anomalies':    { english: 'Loading anomaly data', german: 'Lade Anomaliedaten', french: 'Chargement des données d’anomalies', russian: 'Загрузка данных аномалий' },
    'ui.loading.empires':      { english: 'Loading empire data', german: 'Lade Reichsdaten', french: 'Chargement des données d’empires', russian: 'Загрузка данных империй' },
    'ui.loading.economy':      { english: 'Loading economy data', german: 'Lade Wirtschaftsdaten', french: 'Économie en chargement', russian: 'Загрузка экономических данных' },
    'ui.loading.events':       { english: 'Loading event data', german: 'Lade Ereignisdaten', french: 'Chargement des données d’événements', russian: 'Загрузка данных событий' },
    'ui.loading.generic':      { english: 'Loading...', german: 'Laden...', french: 'Chargement…', russian: 'Загрузка…' },
    'ui.loading.event_details':{ english: 'Loading event details', german: 'Lade Ereignisdetails', french: 'Chargement des détails de l’événement', russian: 'Загрузка подробностей события' },

    'ui.empty.no_items':       { english: 'No items found', german: 'Keine Eintr\u00e4ge gefunden', french: 'Aucun élément trouvé', russian: 'Элементы не найдены' },
    'ui.empty.no_events':      { english: 'No events found', german: 'Keine Ereignisse gefunden', french: 'Aucun événement trouvé', russian: 'События не найдены' },
    'ui.empty.no_results':     { english: 'No results found', german: 'Keine Ergebnisse gefunden', french: 'Aucun résultat trouvé', russian: 'Результаты не найдены' },
    'ui.empty.no_results_any': { english: 'No results found across any module.', german: 'Keine Ergebnisse in allen Modulen gefunden.', french: 'Aucun résultat dans aucun module.', russian: 'Результаты не найдены ни в одном модуле.' },
    'ui.empty.event_not_found':{ english: 'Event not found in detail data', german: 'Ereignis nicht in Detaildaten gefunden', french: 'L’événement est introuvable dans les données de détail', russian: 'Событие не найдено в детальных данных' },
    'ui.empty.other_namespaces': { english: 'Other namespaces', german: 'Andere Namensr\u00e4ume', french: 'Autres espaces de noms', russian: 'Другие пространства имён' },

    'ui.error.load_failed':    { english: 'Failed to load data', german: 'Daten konnten nicht geladen werden', french: 'Impossible de charger les données', russian: 'Не удалось загрузить данные' },
    'ui.error.model_load_failed': { english: 'Could not load 3D model', german: '3D-Modell konnte nicht geladen werden', french: 'Impossible de charger le modèle 3D', russian: 'Не удалось загрузить 3D-модель' },

    // ==========================================
    // Search UI (Hub)
    // ==========================================
    'ui.search.matches':       { english: 'match', german: 'Treffer', french: 'correspondance', russian: 'совпадение' },
    'ui.search.matches_plural':{ english: 'matches', german: 'Treffer', french: 'correspondances', russian: 'совпадения' },
    'ui.search.press_enter':   { english: 'press Enter for full results', german: 'Enter f\u00fcr alle Ergebnisse dr\u00fccken', french: 'appuyez sur Entrée pour les résultats complets', russian: 'нажмите Enter для полных результатов' },
    'ui.search.more':          { english: 'more', german: 'mehr', french: 'plus', russian: 'ещё' },
    'ui.search.back':          { english: 'Back', german: 'Zur\u00fcck', french: 'Retour', russian: 'Назад' },
    'ui.search.all':           { english: 'All', german: 'Alle', french: 'Tous', russian: 'Все' },
    'ui.search.results_for':   { english: 'results for', german: 'Ergebnisse f\u00fcr', french: 'résultats pour', russian: 'результаты по' },
    'ui.search.result':        { english: 'result', german: 'Ergebnis', french: 'résultat', russian: 'результат' },
    'ui.search.results':       { english: 'results', german: 'Ergebnisse', french: 'résultats', russian: 'результаты' },
    'ui.search.also_searching':{ english: 'also searching', german: 'sucht auch nach', french: 'recherche également', russian: 'также ищет' },
    'ui.search.global_results':{ english: 'Cross-module results', german: 'Modul\u00fcbergreifende Ergebnisse', french: 'R\u00e9sultats inter-modules', spanish: 'Resultados multi-m\u00f3dulo', russian: '\u041c\u0435\u0436\u043c\u043e\u0434\u0443\u043b\u044c\u043d\u044b\u0435 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b', polish: 'Wyniki mi\u0119dzymodu\u0142owe', braz_por: 'Resultados entre m\u00f3dulos' },
    'ui.search.global':        { english: 'Search all wiki...', german: 'Gesamtes Wiki durchsuchen...', french: 'Rechercher dans tout le wiki...', spanish: 'Buscar en toda la wiki...', russian: '\u041f\u043e\u0438\u0441\u043a \u043f\u043e \u0432\u0441\u0435\u0439 \u0432\u0438\u043a\u0438...', polish: 'Szukaj w ca\u0142ej wiki...', braz_por: 'Pesquisar em toda a wiki...' },
    'ui.search.global_off':    { english: 'Global search (click to enable)', german: 'Globale Suche (klicken zum Aktivieren)', french: 'Recherche globale (cliquer pour activer)', russian: 'Глобальный поиск (нажмите для включения)' },
    'ui.search.global_on':     { english: 'Global search active (click to disable)', german: 'Globale Suche aktiv (klicken zum Deaktivieren)', french: 'Recherche globale active (cliquer pour désactiver)', russian: 'Глобальный поиск активен (нажмите для отключения)' },
    'ui.search.global_label':  { english: 'Global Search', german: 'Globale Suche', french: 'Recherche globale', russian: 'Глобальный поиск' },

    // ==========================================
    // Misc
    // ==========================================
    'ui.action.view_3d':       { english: 'View 3D Model', german: '3D-Modell anzeigen', french: 'Voir le modèle 3D', russian: 'Посмотреть 3D-модель' },

    'ui.misc.yes':             { english: 'Yes', german: 'Ja', french: 'Oui', russian: 'Да' },
    'ui.misc.stage':           { english: 'Stage', german: 'Stufe', french: 'Étape', russian: 'Этап' },
    'ui.misc.difficulty':      { english: 'difficulty', german: 'Schwierigkeit', french: 'difficulté', russian: 'сложность' },
    'ui.misc.event':           { english: 'Event', german: 'Ereignis', french: 'Événement', russian: 'Событие' },
    'ui.misc.icon':            { english: 'Icon', german: 'Symbol', french: 'Icône', russian: 'Иконка' },
    'ui.misc.unnamed':         { english: '(unnamed)', german: '(unbenannt)', french: '(sans nom)', russian: '(без названия)' },
    'ui.misc.text':            { english: 'Text', german: 'Text', french: 'Texte', russian: 'Текст' },
};
